// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class BroadcastMessage
    {
        [DataMember(Name = "message_id")]
        public ulong MessageId;
        [DataMember(Name = "sender_player_id")]
        public ulong SenderPlayerId;
        [DataMember(Name = "sender_name")]
        public string SenderName;
        [DataMember(Name = "content")]
        public string Content;
        [DataMember(Name = "sent_at")]
        public ulong SentAt;
        [DataMember(Name = "expires_at")]
        public ulong ExpiresAt;

        public BroadcastMessage(
            ulong MessageId,
            ulong SenderPlayerId,
            string SenderName,
            string Content,
            ulong SentAt,
            ulong ExpiresAt
        )
        {
            this.MessageId = MessageId;
            this.SenderPlayerId = SenderPlayerId;
            this.SenderName = SenderName;
            this.Content = Content;
            this.SentAt = SentAt;
            this.ExpiresAt = ExpiresAt;
        }

        public BroadcastMessage()
        {
            this.SenderName = "";
            this.Content = "";
        }
    }
}
