// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class DistributionSphere
    {
        [DataMember(Name = "sphere_id")]
        public ulong SphereId;
        [DataMember(Name = "world_coords")]
        public WorldCoords WorldCoords;
        [DataMember(Name = "cardinal_direction")]
        public string CardinalDirection;
        [DataMember(Name = "sphere_position")]
        public DbVector3 SpherePosition;
        [DataMember(Name = "sphere_radius")]
        public byte SphereRadius;
        [DataMember(Name = "packets_routed")]
        public ulong PacketsRouted;
        [DataMember(Name = "last_packet_time")]
        public SpacetimeDB.Timestamp LastPacketTime;
        [DataMember(Name = "transit_buffer")]
        public System.Collections.Generic.List<WavePacketSample> TransitBuffer;

        public DistributionSphere(
            ulong SphereId,
            WorldCoords WorldCoords,
            string CardinalDirection,
            DbVector3 SpherePosition,
            byte SphereRadius,
            ulong PacketsRouted,
            SpacetimeDB.Timestamp LastPacketTime,
            System.Collections.Generic.List<WavePacketSample> TransitBuffer
        )
        {
            this.SphereId = SphereId;
            this.WorldCoords = WorldCoords;
            this.CardinalDirection = CardinalDirection;
            this.SpherePosition = SpherePosition;
            this.SphereRadius = SphereRadius;
            this.PacketsRouted = PacketsRouted;
            this.LastPacketTime = LastPacketTime;
            this.TransitBuffer = TransitBuffer;
        }

        public DistributionSphere()
        {
            this.WorldCoords = new();
            this.CardinalDirection = "";
            this.SpherePosition = new();
            this.TransitBuffer = new();
        }
    }
}
