// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerChatMessage
    {
        [DataMember(Name = "message_id")]
        public ulong MessageId;
        [DataMember(Name = "sender_player_id")]
        public ulong SenderPlayerId;
        [DataMember(Name = "sender_name")]
        public string SenderName;
        [DataMember(Name = "content")]
        public string Content;
        [DataMember(Name = "position_x")]
        public float PositionX;
        [DataMember(Name = "position_y")]
        public float PositionY;
        [DataMember(Name = "position_z")]
        public float PositionZ;
        [DataMember(Name = "sent_at")]
        public ulong SentAt;
        [DataMember(Name = "expires_at")]
        public ulong ExpiresAt;

        public PlayerChatMessage(
            ulong MessageId,
            ulong SenderPlayerId,
            string SenderName,
            string Content,
            float PositionX,
            float PositionY,
            float PositionZ,
            ulong SentAt,
            ulong ExpiresAt
        )
        {
            this.MessageId = MessageId;
            this.SenderPlayerId = SenderPlayerId;
            this.SenderName = SenderName;
            this.Content = Content;
            this.PositionX = PositionX;
            this.PositionY = PositionY;
            this.PositionZ = PositionZ;
            this.SentAt = SentAt;
            this.ExpiresAt = ExpiresAt;
        }

        public PlayerChatMessage()
        {
            this.SenderName = "";
            this.Content = "";
        }
    }
}
