// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerInventory
    {
        [DataMember(Name = "player_id")]
        public ulong PlayerId;
        [DataMember(Name = "inventory_composition")]
        public System.Collections.Generic.List<WavePacketSample> InventoryComposition;
        [DataMember(Name = "total_count")]
        public uint TotalCount;
        [DataMember(Name = "last_updated")]
        public SpacetimeDB.Timestamp LastUpdated;

        public PlayerInventory(
            ulong PlayerId,
            System.Collections.Generic.List<WavePacketSample> InventoryComposition,
            uint TotalCount,
            SpacetimeDB.Timestamp LastUpdated
        )
        {
            this.PlayerId = PlayerId;
            this.InventoryComposition = InventoryComposition;
            this.TotalCount = TotalCount;
            this.LastUpdated = LastUpdated;
        }

        public PlayerInventory()
        {
            this.InventoryComposition = new();
        }
    }
}
