// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class QuantumTunnel
    {
        [DataMember(Name = "tunnel_id")]
        public ulong TunnelId;
        [DataMember(Name = "world_coords")]
        public WorldCoords WorldCoords;
        [DataMember(Name = "cardinal_direction")]
        public string CardinalDirection;
        [DataMember(Name = "ring_charge")]
        public float RingCharge;
        [DataMember(Name = "tunnel_status")]
        public string TunnelStatus;
        [DataMember(Name = "connected_to_world")]
        public WorldCoords? ConnectedToWorld;
        [DataMember(Name = "connected_to_sphere_id")]
        public ulong? ConnectedToSphereId;
        [DataMember(Name = "tunnel_color")]
        public string TunnelColor;
        [DataMember(Name = "formed_at")]
        public SpacetimeDB.Timestamp? FormedAt;

        public QuantumTunnel(
            ulong TunnelId,
            WorldCoords WorldCoords,
            string CardinalDirection,
            float RingCharge,
            string TunnelStatus,
            WorldCoords? ConnectedToWorld,
            ulong? ConnectedToSphereId,
            string TunnelColor,
            SpacetimeDB.Timestamp? FormedAt
        )
        {
            this.TunnelId = TunnelId;
            this.WorldCoords = WorldCoords;
            this.CardinalDirection = CardinalDirection;
            this.RingCharge = RingCharge;
            this.TunnelStatus = TunnelStatus;
            this.ConnectedToWorld = ConnectedToWorld;
            this.ConnectedToSphereId = ConnectedToSphereId;
            this.TunnelColor = TunnelColor;
            this.FormedAt = FormedAt;
        }

        public QuantumTunnel()
        {
            this.WorldCoords = new();
            this.CardinalDirection = "";
            this.TunnelStatus = "";
            this.TunnelColor = "";
        }
    }
}
