// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class StorageDevice
    {
        [DataMember(Name = "device_id")]
        public ulong DeviceId;
        [DataMember(Name = "owner_player_id")]
        public ulong OwnerPlayerId;
        [DataMember(Name = "world_coords")]
        public WorldCoords WorldCoords;
        [DataMember(Name = "position")]
        public DbVector3 Position;
        [DataMember(Name = "device_name")]
        public string DeviceName;
        [DataMember(Name = "capacity_per_frequency")]
        public uint CapacityPerFrequency;
        [DataMember(Name = "stored_composition")]
        public System.Collections.Generic.List<WavePacketSample> StoredComposition;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;

        public StorageDevice(
            ulong DeviceId,
            ulong OwnerPlayerId,
            WorldCoords WorldCoords,
            DbVector3 Position,
            string DeviceName,
            uint CapacityPerFrequency,
            System.Collections.Generic.List<WavePacketSample> StoredComposition,
            SpacetimeDB.Timestamp CreatedAt
        )
        {
            this.DeviceId = DeviceId;
            this.OwnerPlayerId = OwnerPlayerId;
            this.WorldCoords = WorldCoords;
            this.Position = Position;
            this.DeviceName = DeviceName;
            this.CapacityPerFrequency = CapacityPerFrequency;
            this.StoredComposition = StoredComposition;
            this.CreatedAt = CreatedAt;
        }

        public StorageDevice()
        {
            this.WorldCoords = new();
            this.Position = new();
            this.DeviceName = "";
            this.StoredComposition = new();
        }
    }
}
