// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class WavePacketSample
    {
        [DataMember(Name = "frequency")]
        public float Frequency;
        [DataMember(Name = "amplitude")]
        public float Amplitude;
        [DataMember(Name = "phase")]
        public float Phase;
        [DataMember(Name = "count")]
        public uint Count;

        public WavePacketSample(
            float Frequency,
            float Amplitude,
            float Phase,
            uint Count
        )
        {
            this.Frequency = Frequency;
            this.Amplitude = Amplitude;
            this.Phase = Phase;
            this.Count = Count;
        }

        public WavePacketSample()
        {
        }
    }
}
