// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class WavePacketSource
    {
        [DataMember(Name = "source_id")]
        public ulong SourceId;
        [DataMember(Name = "world_coords")]
        public WorldCoords WorldCoords;
        [DataMember(Name = "position")]
        public DbVector3 Position;
        [DataMember(Name = "velocity")]
        public DbVector3 Velocity;
        [DataMember(Name = "destination")]
        public DbVector3 Destination;
        [DataMember(Name = "state")]
        public byte State;
        [DataMember(Name = "state_start_timestamp")]
        public ulong StateStartTimestamp;
        [DataMember(Name = "wave_packet_composition")]
        public System.Collections.Generic.List<WavePacketSample> WavePacketComposition;
        [DataMember(Name = "total_wave_packets")]
        public uint TotalWavePackets;
        [DataMember(Name = "creation_time")]
        public ulong CreationTime;
        [DataMember(Name = "lifetime_ms")]
        public uint LifetimeMs;
        [DataMember(Name = "last_dissipation")]
        public ulong LastDissipation;
        [DataMember(Name = "active_miner_count")]
        public uint ActiveMinerCount;
        [DataMember(Name = "last_depletion")]
        public ulong LastDepletion;

        public WavePacketSource(
            ulong SourceId,
            WorldCoords WorldCoords,
            DbVector3 Position,
            DbVector3 Velocity,
            DbVector3 Destination,
            byte State,
            ulong StateStartTimestamp,
            System.Collections.Generic.List<WavePacketSample> WavePacketComposition,
            uint TotalWavePackets,
            ulong CreationTime,
            uint LifetimeMs,
            ulong LastDissipation,
            uint ActiveMinerCount,
            ulong LastDepletion
        )
        {
            this.SourceId = SourceId;
            this.WorldCoords = WorldCoords;
            this.Position = Position;
            this.Velocity = Velocity;
            this.Destination = Destination;
            this.State = State;
            this.StateStartTimestamp = StateStartTimestamp;
            this.WavePacketComposition = WavePacketComposition;
            this.TotalWavePackets = TotalWavePackets;
            this.CreationTime = CreationTime;
            this.LifetimeMs = LifetimeMs;
            this.LastDissipation = LastDissipation;
            this.ActiveMinerCount = ActiveMinerCount;
            this.LastDepletion = LastDepletion;
        }

        public WavePacketSource()
        {
            this.WorldCoords = new();
            this.Position = new();
            this.Velocity = new();
            this.Destination = new();
            this.WavePacketComposition = new();
        }
    }
}
