// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class AccountIdentity
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "account_id")]
        public ulong AccountId;

        public AccountIdentity(
            SpacetimeDB.Identity Identity,
            ulong AccountId
        )
        {
            this.Identity = Identity;
            this.AccountId = AccountId;
        }

        public AccountIdentity()
        {
        }
    }
}
