// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Account
    {
        [DataMember(Name = "account_id")]
        public ulong AccountId;
        [DataMember(Name = "username")]
        public string Username;
        [DataMember(Name = "display_name")]
        public string DisplayName;
        [DataMember(Name = "pin_hash")]
        public string PinHash;
        [DataMember(Name = "created_at")]
        public ulong CreatedAt;
        [DataMember(Name = "last_login")]
        public ulong LastLogin;

        public Account(
            ulong AccountId,
            string Username,
            string DisplayName,
            string PinHash,
            ulong CreatedAt,
            ulong LastLogin
        )
        {
            this.AccountId = AccountId;
            this.Username = Username;
            this.DisplayName = DisplayName;
            this.PinHash = PinHash;
            this.CreatedAt = CreatedAt;
            this.LastLogin = LastLogin;
        }

        public Account()
        {
            this.Username = "";
            this.DisplayName = "";
            this.PinHash = "";
        }
    }
}
