// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class AccountIdentity
    {
        [DataMember(Name = "account_id")]
        public ulong AccountId;
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "linked_at")]
        public ulong LinkedAt;

        public AccountIdentity(
            ulong AccountId,
            SpacetimeDB.Identity Identity,
            ulong LinkedAt
        )
        {
            this.AccountId = AccountId;
            this.Identity = Identity;
            this.LinkedAt = LinkedAt;
        }

        public AccountIdentity()
        {
        }
    }
}
