// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class DeviceConnection
    {
        [DataMember(Name = "connection_id")]
        public ulong ConnectionId;
        [DataMember(Name = "device_id")]
        public ulong DeviceId;
        [DataMember(Name = "device_type")]
        public string DeviceType;
        [DataMember(Name = "sphere_id")]
        public ulong SphereId;
        [DataMember(Name = "connection_strength")]
        public float ConnectionStrength;

        public DeviceConnection(
            ulong ConnectionId,
            ulong DeviceId,
            string DeviceType,
            ulong SphereId,
            float ConnectionStrength
        )
        {
            this.ConnectionId = ConnectionId;
            this.DeviceId = DeviceId;
            this.DeviceType = DeviceType;
            this.SphereId = SphereId;
            this.ConnectionStrength = ConnectionStrength;
        }

        public DeviceConnection()
        {
            this.DeviceType = "";
        }
    }
}
