// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class DistributionSphere
    {
        [DataMember(Name = "sphere_id")]
        public ulong SphereId;
        [DataMember(Name = "world_coords")]
        public WorldCoords WorldCoords;
        [DataMember(Name = "position")]
        public DbVector3 Position;
        [DataMember(Name = "coverage_radius")]
        public float CoverageRadius;
        [DataMember(Name = "tunnel_id")]
        public ulong? TunnelId;
        [DataMember(Name = "buffer_capacity")]
        public float BufferCapacity;

        public DistributionSphere(
            ulong SphereId,
            WorldCoords WorldCoords,
            DbVector3 Position,
            float CoverageRadius,
            ulong? TunnelId,
            float BufferCapacity
        )
        {
            this.SphereId = SphereId;
            this.WorldCoords = WorldCoords;
            this.Position = Position;
            this.CoverageRadius = CoverageRadius;
            this.TunnelId = TunnelId;
            this.BufferCapacity = BufferCapacity;
        }

        public DistributionSphere()
        {
            this.WorldCoords = new();
            this.Position = new();
        }
    }
}
