// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class EnergyPuddle
    {
        [DataMember(Name = "puddle_id")]
        public ulong PuddleId;
        [DataMember(Name = "world_coords")]
        public WorldCoords WorldCoords;
        [DataMember(Name = "position")]
        public DbVector3 Position;
        [DataMember(Name = "energy_type")]
        public EnergyType EnergyType;
        [DataMember(Name = "current_amount")]
        public float CurrentAmount;
        [DataMember(Name = "max_amount")]
        public float MaxAmount;

        public EnergyPuddle(
            ulong PuddleId,
            WorldCoords WorldCoords,
            DbVector3 Position,
            EnergyType EnergyType,
            float CurrentAmount,
            float MaxAmount
        )
        {
            this.PuddleId = PuddleId;
            this.WorldCoords = WorldCoords;
            this.Position = Position;
            this.EnergyType = EnergyType;
            this.CurrentAmount = CurrentAmount;
            this.MaxAmount = MaxAmount;
        }

        public EnergyPuddle()
        {
            this.WorldCoords = new();
            this.Position = new();
        }
    }
}
