// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class EnergyTransfer
    {
        [DataMember(Name = "transfer_id")]
        public ulong TransferId;
        [DataMember(Name = "from_device_type")]
        public string FromDeviceType;
        [DataMember(Name = "from_device_id")]
        public ulong FromDeviceId;
        [DataMember(Name = "to_device_type")]
        public string ToDeviceType;
        [DataMember(Name = "to_device_id")]
        public ulong ToDeviceId;
        [DataMember(Name = "energy_type")]
        public EnergyType EnergyType;
        [DataMember(Name = "transfer_rate")]
        public float TransferRate;
        [DataMember(Name = "is_continuous")]
        public bool IsContinuous;
        [DataMember(Name = "route_spheres")]
        public System.Collections.Generic.List<ulong> RouteSpheres;
        [DataMember(Name = "total_cost_per_unit")]
        public float TotalCostPerUnit;

        public EnergyTransfer(
            ulong TransferId,
            string FromDeviceType,
            ulong FromDeviceId,
            string ToDeviceType,
            ulong ToDeviceId,
            EnergyType EnergyType,
            float TransferRate,
            bool IsContinuous,
            System.Collections.Generic.List<ulong> RouteSpheres,
            float TotalCostPerUnit
        )
        {
            this.TransferId = TransferId;
            this.FromDeviceType = FromDeviceType;
            this.FromDeviceId = FromDeviceId;
            this.ToDeviceType = ToDeviceType;
            this.ToDeviceId = ToDeviceId;
            this.EnergyType = EnergyType;
            this.TransferRate = TransferRate;
            this.IsContinuous = IsContinuous;
            this.RouteSpheres = RouteSpheres;
            this.TotalCostPerUnit = TotalCostPerUnit;
        }

        public EnergyTransfer()
        {
            this.FromDeviceType = "";
            this.ToDeviceType = "";
            this.RouteSpheres = new();
        }
    }
}
