// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class EnergySpire
    {
        [DataMember(Name = "spire_id")]
        public ulong SpireId;
        [DataMember(Name = "world_coords")]
        public WorldCoords WorldCoords;
        [DataMember(Name = "sphere_position")]
        public DbVector3 SpherePosition;
        [DataMember(Name = "direction")]
        public string Direction;
        [DataMember(Name = "ring_charge")]
        public float RingCharge;
        [DataMember(Name = "last_charge_time")]
        public SpacetimeDB.Timestamp LastChargeTime;

        public EnergySpire(
            ulong SpireId,
            WorldCoords WorldCoords,
            DbVector3 SpherePosition,
            string Direction,
            float RingCharge,
            SpacetimeDB.Timestamp LastChargeTime
        )
        {
            this.SpireId = SpireId;
            this.WorldCoords = WorldCoords;
            this.SpherePosition = SpherePosition;
            this.Direction = Direction;
            this.RingCharge = RingCharge;
            this.LastChargeTime = LastChargeTime;
        }

        public EnergySpire()
        {
            this.WorldCoords = new();
            this.SpherePosition = new();
            this.Direction = "";
        }
    }
}
