// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class EnergyStorage
    {
        [DataMember(Name = "storage_entry_id")]
        public ulong StorageEntryId;
        [DataMember(Name = "owner_type")]
        public string OwnerType;
        [DataMember(Name = "owner_id")]
        public ulong OwnerId;
        [DataMember(Name = "energy_type")]
        public EnergyType EnergyType;
        [DataMember(Name = "amount")]
        public float Amount;
        [DataMember(Name = "capacity")]
        public float Capacity;

        public EnergyStorage(
            ulong StorageEntryId,
            string OwnerType,
            ulong OwnerId,
            EnergyType EnergyType,
            float Amount,
            float Capacity
        )
        {
            this.StorageEntryId = StorageEntryId;
            this.OwnerType = OwnerType;
            this.OwnerId = OwnerId;
            this.EnergyType = EnergyType;
            this.Amount = Amount;
            this.Capacity = Capacity;
        }

        public EnergyStorage()
        {
            this.OwnerType = "";
        }
    }
}
