// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class EnergyOrb
    {
        [DataMember(Name = "orb_id")]
        public ulong OrbId;
        [DataMember(Name = "world_coords")]
        public WorldCoords WorldCoords;
        [DataMember(Name = "position")]
        public DbVector3 Position;
        [DataMember(Name = "velocity")]
        public DbVector3 Velocity;
        [DataMember(Name = "energy_type")]
        public EnergyType EnergyType;
        [DataMember(Name = "energy_amount")]
        public float EnergyAmount;
        [DataMember(Name = "creation_time")]
        public ulong CreationTime;

        public EnergyOrb(
            ulong OrbId,
            WorldCoords WorldCoords,
            DbVector3 Position,
            DbVector3 Velocity,
            EnergyType EnergyType,
            float EnergyAmount,
            ulong CreationTime
        )
        {
            this.OrbId = OrbId;
            this.WorldCoords = WorldCoords;
            this.Position = Position;
            this.Velocity = Velocity;
            this.EnergyType = EnergyType;
            this.EnergyAmount = EnergyAmount;
            this.CreationTime = CreationTime;
        }

        public EnergyOrb()
        {
            this.WorldCoords = new();
            this.Position = new();
            this.Velocity = new();
        }
    }
}
