// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class GameSettings
    {
        [DataMember(Name = "id")]
        public uint Id;
        [DataMember(Name = "tick_ms")]
        public ulong TickMs;
        [DataMember(Name = "max_players")]
        public uint MaxPlayers;

        public GameSettings(
            uint Id,
            ulong TickMs,
            uint MaxPlayers
        )
        {
            this.Id = Id;
            this.TickMs = TickMs;
            this.MaxPlayers = MaxPlayers;
        }

        public GameSettings()
        {
        }
    }
}
