// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class GameTickCounter
    {
        [DataMember(Name = "id")]
        public uint Id;
        [DataMember(Name = "tick_count")]
        public ulong TickCount;

        public GameTickCounter(
            uint Id,
            ulong TickCount
        )
        {
            this.Id = Id;
            this.TickCount = TickCount;
        }

        public GameTickCounter()
        {
        }
    }
}
