// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class GameSettings
    {
        [DataMember(Name = "setting_key")]
        public string SettingKey;
        [DataMember(Name = "value_type")]
        public string ValueType;
        [DataMember(Name = "value")]
        public string Value;
        [DataMember(Name = "description")]
        public string Description;

        public GameSettings(
            string SettingKey,
            string ValueType,
            string Value,
            string Description
        )
        {
            this.SettingKey = SettingKey;
            this.ValueType = ValueType;
            this.Value = Value;
            this.Description = Description;
        }

        public GameSettings()
        {
            this.SettingKey = "";
            this.ValueType = "";
            this.Value = "";
            this.Description = "";
        }
    }
}
