// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class LoggedOutPlayer
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "player_id")]
        public ulong PlayerId;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "account_id")]
        public ulong? AccountId;
        [DataMember(Name = "logout_time")]
        public SpacetimeDB.Timestamp LogoutTime;

        public LoggedOutPlayer(
            SpacetimeDB.Identity Identity,
            ulong PlayerId,
            string Name,
            ulong? AccountId,
            SpacetimeDB.Timestamp LogoutTime
        )
        {
            this.Identity = Identity;
            this.PlayerId = PlayerId;
            this.Name = Name;
            this.AccountId = AccountId;
            this.LogoutTime = LogoutTime;
        }

        public LoggedOutPlayer()
        {
            this.Name = "";
        }
    }
}
