// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class LoggedOutPlayer
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "player_id")]
        public ulong PlayerId;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "account_id")]
        public ulong? AccountId;
        [DataMember(Name = "logout_time")]
        public SpacetimeDB.Timestamp LogoutTime;
        [DataMember(Name = "last_world")]
        public WorldCoords LastWorld;
        [DataMember(Name = "last_position")]
        public DbVector3 LastPosition;
        [DataMember(Name = "last_rotation")]
        public DbQuaternion LastRotation;

        public LoggedOutPlayer(
            SpacetimeDB.Identity Identity,
            ulong PlayerId,
            string Name,
            ulong? AccountId,
            SpacetimeDB.Timestamp LogoutTime,
            WorldCoords LastWorld,
            DbVector3 LastPosition,
            DbQuaternion LastRotation
        )
        {
            this.Identity = Identity;
            this.PlayerId = PlayerId;
            this.Name = Name;
            this.AccountId = AccountId;
            this.LogoutTime = LogoutTime;
            this.LastWorld = LastWorld;
            this.LastPosition = LastPosition;
            this.LastRotation = LastRotation;
        }

        public LoggedOutPlayer()
        {
            this.Name = "";
            this.LastWorld = new();
            this.LastPosition = new();
            this.LastRotation = new();
        }
    }
}
