// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class LoggedOutPlayer
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "player_data")]
        public Player PlayerData;

        public LoggedOutPlayer(
            SpacetimeDB.Identity Identity,
            Player PlayerData
        )
        {
            this.Identity = Identity;
            this.PlayerData = PlayerData;
        }

        public LoggedOutPlayer()
        {
            this.PlayerData = new();
        }
    }
}
