// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class MinerDevice
    {
        [DataMember(Name = "miner_id")]
        public ulong MinerId;
        [DataMember(Name = "owner_identity")]
        public SpacetimeDB.Identity OwnerIdentity;
        [DataMember(Name = "world_coords")]
        public WorldCoords WorldCoords;
        [DataMember(Name = "position")]
        public DbVector3 Position;
        [DataMember(Name = "target_puddle_id")]
        public ulong? TargetPuddleId;
        [DataMember(Name = "efficiency_bonus")]
        public float EfficiencyBonus;
        [DataMember(Name = "storage_capacity")]
        public float StorageCapacity;

        public MinerDevice(
            ulong MinerId,
            SpacetimeDB.Identity OwnerIdentity,
            WorldCoords WorldCoords,
            DbVector3 Position,
            ulong? TargetPuddleId,
            float EfficiencyBonus,
            float StorageCapacity
        )
        {
            this.MinerId = MinerId;
            this.OwnerIdentity = OwnerIdentity;
            this.WorldCoords = WorldCoords;
            this.Position = Position;
            this.TargetPuddleId = TargetPuddleId;
            this.EfficiencyBonus = EfficiencyBonus;
            this.StorageCapacity = StorageCapacity;
        }

        public MinerDevice()
        {
            this.WorldCoords = new();
            this.Position = new();
        }
    }
}
