// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class MiningSession
    {
        [DataMember(Name = "session_id")]
        public ulong SessionId;
        [DataMember(Name = "player_identity")]
        public SpacetimeDB.Identity PlayerIdentity;
        [DataMember(Name = "orb_id")]
        public ulong OrbId;
        [DataMember(Name = "circuit_id")]
        public ulong CircuitId;
        [DataMember(Name = "started_at")]
        public ulong StartedAt;
        [DataMember(Name = "last_extraction")]
        public ulong LastExtraction;
        [DataMember(Name = "extraction_multiplier")]
        public float ExtractionMultiplier;
        [DataMember(Name = "total_extracted")]
        public uint TotalExtracted;
        [DataMember(Name = "is_active")]
        public bool IsActive;

        public MiningSession(
            ulong SessionId,
            SpacetimeDB.Identity PlayerIdentity,
            ulong OrbId,
            ulong CircuitId,
            ulong StartedAt,
            ulong LastExtraction,
            float ExtractionMultiplier,
            uint TotalExtracted,
            bool IsActive
        )
        {
            this.SessionId = SessionId;
            this.PlayerIdentity = PlayerIdentity;
            this.OrbId = OrbId;
            this.CircuitId = CircuitId;
            this.StartedAt = StartedAt;
            this.LastExtraction = LastExtraction;
            this.ExtractionMultiplier = ExtractionMultiplier;
            this.TotalExtracted = TotalExtracted;
            this.IsActive = IsActive;
        }

        public MiningSession()
        {
        }
    }
}
