// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PacketTransfer
    {
        [DataMember(Name = "transfer_id")]
        public ulong TransferId;
        [DataMember(Name = "player_id")]
        public ulong PlayerId;
        [DataMember(Name = "composition")]
        public System.Collections.Generic.List<WavePacketSample> Composition;
        [DataMember(Name = "packet_count")]
        public uint PacketCount;
        [DataMember(Name = "route_waypoints")]
        public System.Collections.Generic.List<DbVector3> RouteWaypoints;
        [DataMember(Name = "route_spire_ids")]
        public System.Collections.Generic.List<ulong> RouteSpireIds;
        [DataMember(Name = "destination_device_id")]
        public ulong DestinationDeviceId;
        [DataMember(Name = "initiated_at")]
        public SpacetimeDB.Timestamp InitiatedAt;
        [DataMember(Name = "completed")]
        public bool Completed;

        public PacketTransfer(
            ulong TransferId,
            ulong PlayerId,
            System.Collections.Generic.List<WavePacketSample> Composition,
            uint PacketCount,
            System.Collections.Generic.List<DbVector3> RouteWaypoints,
            System.Collections.Generic.List<ulong> RouteSpireIds,
            ulong DestinationDeviceId,
            SpacetimeDB.Timestamp InitiatedAt,
            bool Completed
        )
        {
            this.TransferId = TransferId;
            this.PlayerId = PlayerId;
            this.Composition = Composition;
            this.PacketCount = PacketCount;
            this.RouteWaypoints = RouteWaypoints;
            this.RouteSpireIds = RouteSpireIds;
            this.DestinationDeviceId = DestinationDeviceId;
            this.InitiatedAt = InitiatedAt;
            this.Completed = Completed;
        }

        public PacketTransfer()
        {
            this.Composition = new();
            this.RouteWaypoints = new();
            this.RouteSpireIds = new();
        }
    }
}
