// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerSession
    {
        [DataMember(Name = "session_id")]
        public ulong SessionId;
        [DataMember(Name = "account_id")]
        public ulong AccountId;
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "session_token")]
        public string SessionToken;
        [DataMember(Name = "device_info")]
        public string DeviceInfo;
        [DataMember(Name = "created_at")]
        public ulong CreatedAt;
        [DataMember(Name = "expires_at")]
        public ulong ExpiresAt;
        [DataMember(Name = "last_activity")]
        public ulong LastActivity;
        [DataMember(Name = "is_active")]
        public bool IsActive;

        public PlayerSession(
            ulong SessionId,
            ulong AccountId,
            SpacetimeDB.Identity Identity,
            string SessionToken,
            string DeviceInfo,
            ulong CreatedAt,
            ulong ExpiresAt,
            ulong LastActivity,
            bool IsActive
        )
        {
            this.SessionId = SessionId;
            this.AccountId = AccountId;
            this.Identity = Identity;
            this.SessionToken = SessionToken;
            this.DeviceInfo = DeviceInfo;
            this.CreatedAt = CreatedAt;
            this.ExpiresAt = ExpiresAt;
            this.LastActivity = LastActivity;
            this.IsActive = IsActive;
        }

        public PlayerSession()
        {
            this.SessionToken = "";
            this.DeviceInfo = "";
        }
    }
}
