// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Player
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "player_id")]
        public ulong PlayerId;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "current_world")]
        public WorldCoords CurrentWorld;
        [DataMember(Name = "position")]
        public DbVector3 Position;
        [DataMember(Name = "rotation")]
        public DbVector3 Rotation;
        [DataMember(Name = "last_update")]
        public SpacetimeDB.Timestamp LastUpdate;

        public Player(
            SpacetimeDB.Identity Identity,
            ulong PlayerId,
            string Name,
            WorldCoords CurrentWorld,
            DbVector3 Position,
            DbVector3 Rotation,
            SpacetimeDB.Timestamp LastUpdate
        )
        {
            this.Identity = Identity;
            this.PlayerId = PlayerId;
            this.Name = Name;
            this.CurrentWorld = CurrentWorld;
            this.Position = Position;
            this.Rotation = Rotation;
            this.LastUpdate = LastUpdate;
        }

        public Player()
        {
            this.Name = "";
            this.CurrentWorld = new();
            this.Position = new();
            this.Rotation = new();
        }
    }
}
