// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerInventory
    {
        [DataMember(Name = "player_id")]
        public ulong PlayerId;
        [DataMember(Name = "red_count")]
        public uint RedCount;
        [DataMember(Name = "yellow_count")]
        public uint YellowCount;
        [DataMember(Name = "green_count")]
        public uint GreenCount;
        [DataMember(Name = "cyan_count")]
        public uint CyanCount;
        [DataMember(Name = "blue_count")]
        public uint BlueCount;
        [DataMember(Name = "magenta_count")]
        public uint MagentaCount;
        [DataMember(Name = "total_count")]
        public uint TotalCount;
        [DataMember(Name = "last_updated")]
        public SpacetimeDB.Timestamp LastUpdated;

        public PlayerInventory(
            ulong PlayerId,
            uint RedCount,
            uint YellowCount,
            uint GreenCount,
            uint CyanCount,
            uint BlueCount,
            uint MagentaCount,
            uint TotalCount,
            SpacetimeDB.Timestamp LastUpdated
        )
        {
            this.PlayerId = PlayerId;
            this.RedCount = RedCount;
            this.YellowCount = YellowCount;
            this.GreenCount = GreenCount;
            this.CyanCount = CyanCount;
            this.BlueCount = BlueCount;
            this.MagentaCount = MagentaCount;
            this.TotalCount = TotalCount;
            this.LastUpdated = LastUpdated;
        }

        public PlayerInventory()
        {
        }
    }
}
