// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class QuantaSignature
    {
        [DataMember(Name = "frequency")]
        public float Frequency;
        [DataMember(Name = "resonance")]
        public float Resonance;
        [DataMember(Name = "flux_pattern")]
        public ushort FluxPattern;

        public QuantaSignature(
            float Frequency,
            float Resonance,
            ushort FluxPattern
        )
        {
            this.Frequency = Frequency;
            this.Resonance = Resonance;
            this.FluxPattern = FluxPattern;
        }

        public QuantaSignature()
        {
        }
    }
}
