// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class QuantaOrb
    {
        [DataMember(Name = "orb_id")]
        public ulong OrbId;
        [DataMember(Name = "world_coords")]
        public WorldCoords WorldCoords;
        [DataMember(Name = "position")]
        public DbVector3 Position;
        [DataMember(Name = "velocity")]
        public DbVector3 Velocity;
        [DataMember(Name = "signature")]
        public QuantaSignature Signature;
        [DataMember(Name = "quanta_amount")]
        public uint QuantaAmount;
        [DataMember(Name = "creation_time")]
        public ulong CreationTime;
        [DataMember(Name = "lifetime_ms")]
        public uint LifetimeMs;

        public QuantaOrb(
            ulong OrbId,
            WorldCoords WorldCoords,
            DbVector3 Position,
            DbVector3 Velocity,
            QuantaSignature Signature,
            uint QuantaAmount,
            ulong CreationTime,
            uint LifetimeMs
        )
        {
            this.OrbId = OrbId;
            this.WorldCoords = WorldCoords;
            this.Position = Position;
            this.Velocity = Velocity;
            this.Signature = Signature;
            this.QuantaAmount = QuantaAmount;
            this.CreationTime = CreationTime;
            this.LifetimeMs = LifetimeMs;
        }

        public QuantaOrb()
        {
            this.WorldCoords = new();
            this.Position = new();
            this.Velocity = new();
            this.Signature = new();
        }
    }
}
