// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class SessionResult
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "session_token")]
        public string SessionToken;
        [DataMember(Name = "created_at")]
        public ulong CreatedAt;

        public SessionResult(
            SpacetimeDB.Identity Identity,
            string SessionToken,
            ulong CreatedAt
        )
        {
            this.Identity = Identity;
            this.SessionToken = SessionToken;
            this.CreatedAt = CreatedAt;
        }

        public SessionResult()
        {
            this.SessionToken = "";
        }
    }
}
