// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class SimpleEnergyDiscovery
    {
        [DataMember(Name = "signature_hash")]
        public ulong SignatureHash;
        [DataMember(Name = "signature")]
        public SimpleEnergySignature Signature;
        [DataMember(Name = "display_name")]
        public string DisplayName;
        [DataMember(Name = "discovered_by")]
        public SpacetimeDB.Identity DiscoveredBy;
        [DataMember(Name = "discovery_time")]
        public ulong DiscoveryTime;
        [DataMember(Name = "shell_origin")]
        public byte ShellOrigin;
        [DataMember(Name = "discovery_count")]
        public uint DiscoveryCount;

        public SimpleEnergyDiscovery(
            ulong SignatureHash,
            SimpleEnergySignature Signature,
            string DisplayName,
            SpacetimeDB.Identity DiscoveredBy,
            ulong DiscoveryTime,
            byte ShellOrigin,
            uint DiscoveryCount
        )
        {
            this.SignatureHash = SignatureHash;
            this.Signature = Signature;
            this.DisplayName = DisplayName;
            this.DiscoveredBy = DiscoveredBy;
            this.DiscoveryTime = DiscoveryTime;
            this.ShellOrigin = ShellOrigin;
            this.DiscoveryCount = DiscoveryCount;
        }

        public SimpleEnergyDiscovery()
        {
            this.Signature = new();
            this.DisplayName = "";
        }
    }
}
