// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class SimpleEnergyOrb
    {
        [DataMember(Name = "orb_id")]
        public ulong OrbId;
        [DataMember(Name = "world_coords")]
        public WorldCoords WorldCoords;
        [DataMember(Name = "position")]
        public DbVector3 Position;
        [DataMember(Name = "velocity")]
        public DbVector3 Velocity;
        [DataMember(Name = "energy_signature")]
        public SimpleEnergySignature EnergySignature;
        [DataMember(Name = "quantum_count")]
        public uint QuantumCount;
        [DataMember(Name = "creation_time")]
        public ulong CreationTime;

        public SimpleEnergyOrb(
            ulong OrbId,
            WorldCoords WorldCoords,
            DbVector3 Position,
            DbVector3 Velocity,
            SimpleEnergySignature EnergySignature,
            uint QuantumCount,
            ulong CreationTime
        )
        {
            this.OrbId = OrbId;
            this.WorldCoords = WorldCoords;
            this.Position = Position;
            this.Velocity = Velocity;
            this.EnergySignature = EnergySignature;
            this.QuantumCount = QuantumCount;
            this.CreationTime = CreationTime;
        }

        public SimpleEnergyOrb()
        {
            this.WorldCoords = new();
            this.Position = new();
            this.Velocity = new();
            this.EnergySignature = new();
        }
    }
}
