// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class SimpleEnergySignature
    {
        [DataMember(Name = "frequency")]
        public float Frequency;

        public SimpleEnergySignature(float Frequency)
        {
            this.Frequency = Frequency;
        }

        public SimpleEnergySignature()
        {
        }
    }
}
