// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class SimpleEnergyStorage
    {
        [DataMember(Name = "storage_id")]
        public ulong StorageId;
        [DataMember(Name = "owner_type")]
        public string OwnerType;
        [DataMember(Name = "owner_id")]
        public ulong OwnerId;
        [DataMember(Name = "energy_signature")]
        public SimpleEnergySignature EnergySignature;
        [DataMember(Name = "quantum_count")]
        public uint QuantumCount;
        [DataMember(Name = "last_update")]
        public ulong LastUpdate;

        public SimpleEnergyStorage(
            ulong StorageId,
            string OwnerType,
            ulong OwnerId,
            SimpleEnergySignature EnergySignature,
            uint QuantumCount,
            ulong LastUpdate
        )
        {
            this.StorageId = StorageId;
            this.OwnerType = OwnerType;
            this.OwnerId = OwnerId;
            this.EnergySignature = EnergySignature;
            this.QuantumCount = QuantumCount;
            this.LastUpdate = LastUpdate;
        }

        public SimpleEnergyStorage()
        {
            this.OwnerType = "";
            this.EnergySignature = new();
        }
    }
}
