// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class StorageDevice
    {
        [DataMember(Name = "device_id")]
        public ulong DeviceId;
        [DataMember(Name = "owner_player_id")]
        public ulong OwnerPlayerId;
        [DataMember(Name = "world_coords")]
        public WorldCoords WorldCoords;
        [DataMember(Name = "position")]
        public DbVector3 Position;
        [DataMember(Name = "capacity")]
        public uint Capacity;
        [DataMember(Name = "current_count")]
        public uint CurrentCount;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;

        public StorageDevice(
            ulong DeviceId,
            ulong OwnerPlayerId,
            WorldCoords WorldCoords,
            DbVector3 Position,
            uint Capacity,
            uint CurrentCount,
            SpacetimeDB.Timestamp CreatedAt
        )
        {
            this.DeviceId = DeviceId;
            this.OwnerPlayerId = OwnerPlayerId;
            this.WorldCoords = WorldCoords;
            this.Position = Position;
            this.Capacity = Capacity;
            this.CurrentCount = CurrentCount;
            this.CreatedAt = CreatedAt;
        }

        public StorageDevice()
        {
            this.WorldCoords = new();
            this.Position = new();
        }
    }
}
