// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class StorageDevice
    {
        [DataMember(Name = "storage_id")]
        public ulong StorageId;
        [DataMember(Name = "owner_identity")]
        public SpacetimeDB.Identity OwnerIdentity;
        [DataMember(Name = "world_coords")]
        public WorldCoords WorldCoords;
        [DataMember(Name = "position")]
        public DbVector3 Position;
        [DataMember(Name = "energy_red")]
        public float EnergyRed;
        [DataMember(Name = "energy_green")]
        public float EnergyGreen;
        [DataMember(Name = "energy_blue")]
        public float EnergyBlue;
        [DataMember(Name = "storage_capacity")]
        public float StorageCapacity;

        public StorageDevice(
            ulong StorageId,
            SpacetimeDB.Identity OwnerIdentity,
            WorldCoords WorldCoords,
            DbVector3 Position,
            float EnergyRed,
            float EnergyGreen,
            float EnergyBlue,
            float StorageCapacity
        )
        {
            this.StorageId = StorageId;
            this.OwnerIdentity = OwnerIdentity;
            this.WorldCoords = WorldCoords;
            this.Position = Position;
            this.EnergyRed = EnergyRed;
            this.EnergyGreen = EnergyGreen;
            this.EnergyBlue = EnergyBlue;
            this.StorageCapacity = StorageCapacity;
        }

        public StorageDevice()
        {
            this.WorldCoords = new();
            this.Position = new();
        }
    }
}
