// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Tunnel
    {
        [DataMember(Name = "tunnel_id")]
        public ulong TunnelId;
        [DataMember(Name = "from_world")]
        public WorldCoords FromWorld;
        [DataMember(Name = "to_world")]
        public WorldCoords ToWorld;
        [DataMember(Name = "activation_progress")]
        public float ActivationProgress;
        [DataMember(Name = "activation_threshold")]
        public float ActivationThreshold;
        [DataMember(Name = "status")]
        public string Status;
        [DataMember(Name = "transfer_cost_multiplier")]
        public float TransferCostMultiplier;

        public Tunnel(
            ulong TunnelId,
            WorldCoords FromWorld,
            WorldCoords ToWorld,
            float ActivationProgress,
            float ActivationThreshold,
            string Status,
            float TransferCostMultiplier
        )
        {
            this.TunnelId = TunnelId;
            this.FromWorld = FromWorld;
            this.ToWorld = ToWorld;
            this.ActivationProgress = ActivationProgress;
            this.ActivationThreshold = ActivationThreshold;
            this.Status = Status;
            this.TransferCostMultiplier = TransferCostMultiplier;
        }

        public Tunnel()
        {
            this.FromWorld = new();
            this.ToWorld = new();
            this.Status = "";
        }
    }
}
