// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class UserAccount
    {
        [DataMember(Name = "account_id")]
        public ulong AccountId;
        [DataMember(Name = "username")]
        public string Username;
        [DataMember(Name = "password_hash")]
        public string PasswordHash;
        [DataMember(Name = "salt")]
        public string Salt;
        [DataMember(Name = "created_at")]
        public ulong CreatedAt;
        [DataMember(Name = "last_login")]
        public ulong LastLogin;

        public UserAccount(
            ulong AccountId,
            string Username,
            string PasswordHash,
            string Salt,
            ulong CreatedAt,
            ulong LastLogin
        )
        {
            this.AccountId = AccountId;
            this.Username = Username;
            this.PasswordHash = PasswordHash;
            this.Salt = Salt;
            this.CreatedAt = CreatedAt;
            this.LastLogin = LastLogin;
        }

        public UserAccount()
        {
            this.Username = "";
            this.PasswordHash = "";
            this.Salt = "";
        }
    }
}
