// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class WavePacketSample
    {
        [DataMember(Name = "signature")]
        public WavePacketSignature Signature;
        [DataMember(Name = "amount")]
        public uint Amount;
        [DataMember(Name = "source_shell")]
        public byte SourceShell;

        public WavePacketSample(
            WavePacketSignature Signature,
            uint Amount,
            byte SourceShell
        )
        {
            this.Signature = Signature;
            this.Amount = Amount;
            this.SourceShell = SourceShell;
        }

        public WavePacketSample()
        {
            this.Signature = new();
        }
    }
}
