// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class WavePacketStorage
    {
        [DataMember(Name = "storage_id")]
        public ulong StorageId;
        [DataMember(Name = "owner_type")]
        public string OwnerType;
        [DataMember(Name = "owner_id")]
        public ulong OwnerId;
        [DataMember(Name = "frequency_band")]
        public FrequencyBand FrequencyBand;
        [DataMember(Name = "total_wave_packets")]
        public uint TotalWavePackets;
        [DataMember(Name = "signature_samples")]
        public System.Collections.Generic.List<WavePacketSample> SignatureSamples;
        [DataMember(Name = "last_update")]
        public ulong LastUpdate;

        public WavePacketStorage(
            ulong StorageId,
            string OwnerType,
            ulong OwnerId,
            FrequencyBand FrequencyBand,
            uint TotalWavePackets,
            System.Collections.Generic.List<WavePacketSample> SignatureSamples,
            ulong LastUpdate
        )
        {
            this.StorageId = StorageId;
            this.OwnerType = OwnerType;
            this.OwnerId = OwnerId;
            this.FrequencyBand = FrequencyBand;
            this.TotalWavePackets = TotalWavePackets;
            this.SignatureSamples = SignatureSamples;
            this.LastUpdate = LastUpdate;
        }

        public WavePacketStorage()
        {
            this.OwnerType = "";
            this.SignatureSamples = new();
        }
    }
}
