// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class WavePacketExtraction
    {
        [DataMember(Name = "extraction_id")]
        public ulong ExtractionId;
        [DataMember(Name = "player_id")]
        public ulong PlayerId;
        [DataMember(Name = "source_type")]
        public string SourceType;
        [DataMember(Name = "source_id")]
        public ulong SourceId;
        [DataMember(Name = "packet_id")]
        public ulong PacketId;
        [DataMember(Name = "composition")]
        public System.Collections.Generic.List<WavePacketSample> Composition;
        [DataMember(Name = "total_count")]
        public uint TotalCount;
        [DataMember(Name = "departure_time")]
        public ulong DepartureTime;
        [DataMember(Name = "expected_arrival")]
        public ulong ExpectedArrival;

        public WavePacketExtraction(
            ulong ExtractionId,
            ulong PlayerId,
            string SourceType,
            ulong SourceId,
            ulong PacketId,
            System.Collections.Generic.List<WavePacketSample> Composition,
            uint TotalCount,
            ulong DepartureTime,
            ulong ExpectedArrival
        )
        {
            this.ExtractionId = ExtractionId;
            this.PlayerId = PlayerId;
            this.SourceType = SourceType;
            this.SourceId = SourceId;
            this.PacketId = PacketId;
            this.Composition = Composition;
            this.TotalCount = TotalCount;
            this.DepartureTime = DepartureTime;
            this.ExpectedArrival = ExpectedArrival;
        }

        public WavePacketExtraction()
        {
            this.SourceType = "";
            this.Composition = new();
        }
    }
}
