// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class WavePacketExtraction
    {
        [DataMember(Name = "extraction_id")]
        public ulong ExtractionId;
        [DataMember(Name = "player_id")]
        public ulong PlayerId;
        [DataMember(Name = "wave_packet_id")]
        public ulong WavePacketId;
        [DataMember(Name = "signature")]
        public WavePacketSignature Signature;
        [DataMember(Name = "departure_time")]
        public ulong DepartureTime;
        [DataMember(Name = "expected_arrival")]
        public ulong ExpectedArrival;

        public WavePacketExtraction(
            ulong ExtractionId,
            ulong PlayerId,
            ulong WavePacketId,
            WavePacketSignature Signature,
            ulong DepartureTime,
            ulong ExpectedArrival
        )
        {
            this.ExtractionId = ExtractionId;
            this.PlayerId = PlayerId;
            this.WavePacketId = WavePacketId;
            this.Signature = Signature;
            this.DepartureTime = DepartureTime;
            this.ExpectedArrival = ExpectedArrival;
        }

        public WavePacketExtraction()
        {
            this.Signature = new();
        }
    }
}
