// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class WorldCircuit
    {
        [DataMember(Name = "world_coords")]
        public WorldCoords WorldCoords;
        [DataMember(Name = "circuit_id")]
        public ulong CircuitId;
        [DataMember(Name = "qubit_count")]
        public byte QubitCount;
        [DataMember(Name = "emission_interval_ms")]
        public ulong EmissionIntervalMs;
        [DataMember(Name = "orbs_per_emission")]
        public uint OrbsPerEmission;
        [DataMember(Name = "last_emission_time")]
        public ulong LastEmissionTime;

        public WorldCircuit(
            WorldCoords WorldCoords,
            ulong CircuitId,
            byte QubitCount,
            ulong EmissionIntervalMs,
            uint OrbsPerEmission,
            ulong LastEmissionTime
        )
        {
            this.WorldCoords = WorldCoords;
            this.CircuitId = CircuitId;
            this.QubitCount = QubitCount;
            this.EmissionIntervalMs = EmissionIntervalMs;
            this.OrbsPerEmission = OrbsPerEmission;
            this.LastEmissionTime = LastEmissionTime;
        }

        public WorldCircuit()
        {
            this.WorldCoords = new();
        }
    }
}
