// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class World
    {
        [DataMember(Name = "world_coords")]
        public WorldCoords WorldCoords;
        [DataMember(Name = "shell_level")]
        public byte ShellLevel;
        [DataMember(Name = "radius")]
        public float Radius;
        [DataMember(Name = "circuit_qubit_count")]
        public byte CircuitQubitCount;
        [DataMember(Name = "status")]
        public string Status;

        public World(
            WorldCoords WorldCoords,
            byte ShellLevel,
            float Radius,
            byte CircuitQubitCount,
            string Status
        )
        {
            this.WorldCoords = WorldCoords;
            this.ShellLevel = ShellLevel;
            this.Radius = Radius;
            this.CircuitQubitCount = CircuitQubitCount;
            this.Status = Status;
        }

        public World()
        {
            this.WorldCoords = new();
            this.Status = "";
        }
    }
}
