// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class WorldCircuit
    {
        [DataMember(Name = "circuit_id")]
        public ulong CircuitId;
        [DataMember(Name = "world_coords")]
        public WorldCoords WorldCoords;
        [DataMember(Name = "cardinal_direction")]
        public string CardinalDirection;
        [DataMember(Name = "circuit_type")]
        public string CircuitType;
        [DataMember(Name = "qubit_count")]
        public byte QubitCount;
        [DataMember(Name = "orbs_per_emission")]
        public uint OrbsPerEmission;
        [DataMember(Name = "emission_interval_ms")]
        public ulong EmissionIntervalMs;
        [DataMember(Name = "last_emission_time")]
        public ulong LastEmissionTime;

        public WorldCircuit(
            ulong CircuitId,
            WorldCoords WorldCoords,
            string CardinalDirection,
            string CircuitType,
            byte QubitCount,
            uint OrbsPerEmission,
            ulong EmissionIntervalMs,
            ulong LastEmissionTime
        )
        {
            this.CircuitId = CircuitId;
            this.WorldCoords = WorldCoords;
            this.CardinalDirection = CardinalDirection;
            this.CircuitType = CircuitType;
            this.QubitCount = QubitCount;
            this.OrbsPerEmission = OrbsPerEmission;
            this.EmissionIntervalMs = EmissionIntervalMs;
            this.LastEmissionTime = LastEmissionTime;
        }

        public WorldCircuit()
        {
            this.WorldCoords = new();
            this.CardinalDirection = "";
            this.CircuitType = "";
        }
    }
}
