// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class WorldCoords
    {
        [DataMember(Name = "x")]
        public sbyte X;
        [DataMember(Name = "y")]
        public sbyte Y;
        [DataMember(Name = "z")]
        public sbyte Z;

        public WorldCoords(
            sbyte X,
            sbyte Y,
            sbyte Z
        )
        {
            this.X = X;
            this.Y = Y;
            this.Z = Z;
        }

        public WorldCoords()
        {
        }
    }
}
