// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AddTestInventoryHandler(ReducerEventContext ctx, ulong playerId, uint red, uint yellow, uint green, uint cyan, uint blue, uint magenta);
        public event AddTestInventoryHandler? OnAddTestInventory;

        public void AddTestInventory(ulong playerId, uint red, uint yellow, uint green, uint cyan, uint blue, uint magenta)
        {
            conn.InternalCallReducer(new Reducer.AddTestInventory(playerId, red, yellow, green, cyan, blue, magenta), this.SetCallReducerFlags.AddTestInventoryFlags);
        }

        public bool InvokeAddTestInventory(ReducerEventContext ctx, Reducer.AddTestInventory args)
        {
            if (OnAddTestInventory == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAddTestInventory(
                ctx,
                args.PlayerId,
                args.Red,
                args.Yellow,
                args.Green,
                args.Cyan,
                args.Blue,
                args.Magenta
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AddTestInventory : Reducer, IReducerArgs
        {
            [DataMember(Name = "player_id")]
            public ulong PlayerId;
            [DataMember(Name = "red")]
            public uint Red;
            [DataMember(Name = "yellow")]
            public uint Yellow;
            [DataMember(Name = "green")]
            public uint Green;
            [DataMember(Name = "cyan")]
            public uint Cyan;
            [DataMember(Name = "blue")]
            public uint Blue;
            [DataMember(Name = "magenta")]
            public uint Magenta;

            public AddTestInventory(
                ulong PlayerId,
                uint Red,
                uint Yellow,
                uint Green,
                uint Cyan,
                uint Blue,
                uint Magenta
            )
            {
                this.PlayerId = PlayerId;
                this.Red = Red;
                this.Yellow = Yellow;
                this.Green = Green;
                this.Cyan = Cyan;
                this.Blue = Blue;
                this.Magenta = Magenta;
            }

            public AddTestInventory()
            {
            }

            string IReducerArgs.ReducerName => "add_test_inventory";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AddTestInventoryFlags;
        public void AddTestInventory(CallReducerFlags flags) => AddTestInventoryFlags = flags;
    }
}
