// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CaptureExtractedPacketV2Handler(ReducerEventContext ctx, ulong packetId);
        public event CaptureExtractedPacketV2Handler? OnCaptureExtractedPacketV2;

        public void CaptureExtractedPacketV2(ulong packetId)
        {
            conn.InternalCallReducer(new Reducer.CaptureExtractedPacketV2(packetId), this.SetCallReducerFlags.CaptureExtractedPacketV2Flags);
        }

        public bool InvokeCaptureExtractedPacketV2(ReducerEventContext ctx, Reducer.CaptureExtractedPacketV2 args)
        {
            if (OnCaptureExtractedPacketV2 == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCaptureExtractedPacketV2(
                ctx,
                args.PacketId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CaptureExtractedPacketV2 : Reducer, IReducerArgs
        {
            [DataMember(Name = "packet_id")]
            public ulong PacketId;

            public CaptureExtractedPacketV2(ulong PacketId)
            {
                this.PacketId = PacketId;
            }

            public CaptureExtractedPacketV2()
            {
            }

            string IReducerArgs.ReducerName => "capture_extracted_packet_v2";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags CaptureExtractedPacketV2Flags;
        public void CaptureExtractedPacketV2(CallReducerFlags flags) => CaptureExtractedPacketV2Flags = flags;
    }
}
