// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CheckAndSpawnWorldHandler(ReducerEventContext ctx, int x, int y, int z);
        public event CheckAndSpawnWorldHandler? OnCheckAndSpawnWorld;

        public void CheckAndSpawnWorld(int x, int y, int z)
        {
            conn.InternalCallReducer(new Reducer.CheckAndSpawnWorld(x, y, z), this.SetCallReducerFlags.CheckAndSpawnWorldFlags);
        }

        public bool InvokeCheckAndSpawnWorld(ReducerEventContext ctx, Reducer.CheckAndSpawnWorld args)
        {
            if (OnCheckAndSpawnWorld == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCheckAndSpawnWorld(
                ctx,
                args.X,
                args.Y,
                args.Z
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CheckAndSpawnWorld : Reducer, IReducerArgs
        {
            [DataMember(Name = "x")]
            public int X;
            [DataMember(Name = "y")]
            public int Y;
            [DataMember(Name = "z")]
            public int Z;

            public CheckAndSpawnWorld(
                int X,
                int Y,
                int Z
            )
            {
                this.X = X;
                this.Y = Y;
                this.Z = Z;
            }

            public CheckAndSpawnWorld()
            {
            }

            string IReducerArgs.ReducerName => "check_and_spawn_world";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags CheckAndSpawnWorldFlags;
        public void CheckAndSpawnWorld(CallReducerFlags flags) => CheckAndSpawnWorldFlags = flags;
    }
}
