// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ClaimMiningSessionPacketsHandler(ReducerEventContext ctx, ulong sessionId);
        public event ClaimMiningSessionPacketsHandler? OnClaimMiningSessionPackets;

        public void ClaimMiningSessionPackets(ulong sessionId)
        {
            conn.InternalCallReducer(new Reducer.ClaimMiningSessionPackets(sessionId), this.SetCallReducerFlags.ClaimMiningSessionPacketsFlags);
        }

        public bool InvokeClaimMiningSessionPackets(ReducerEventContext ctx, Reducer.ClaimMiningSessionPackets args)
        {
            if (OnClaimMiningSessionPackets == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnClaimMiningSessionPackets(
                ctx,
                args.SessionId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ClaimMiningSessionPackets : Reducer, IReducerArgs
        {
            [DataMember(Name = "session_id")]
            public ulong SessionId;

            public ClaimMiningSessionPackets(ulong SessionId)
            {
                this.SessionId = SessionId;
            }

            public ClaimMiningSessionPackets()
            {
            }

            string IReducerArgs.ReducerName => "claim_mining_session_packets";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ClaimMiningSessionPacketsFlags;
        public void ClaimMiningSessionPackets(CallReducerFlags flags) => ClaimMiningSessionPacketsFlags = flags;
    }
}
