// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ClearAllStorageDevicesHandler(ReducerEventContext ctx);
        public event ClearAllStorageDevicesHandler? OnClearAllStorageDevices;

        public void ClearAllStorageDevices()
        {
            conn.InternalCallReducer(new Reducer.ClearAllStorageDevices(), this.SetCallReducerFlags.ClearAllStorageDevicesFlags);
        }

        public bool InvokeClearAllStorageDevices(ReducerEventContext ctx, Reducer.ClearAllStorageDevices args)
        {
            if (OnClearAllStorageDevices == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnClearAllStorageDevices(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ClearAllStorageDevices : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "clear_all_storage_devices";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ClearAllStorageDevicesFlags;
        public void ClearAllStorageDevices(CallReducerFlags flags) => ClearAllStorageDevicesFlags = flags;
    }
}
