// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CreateStorageDeviceHandler(ReducerEventContext ctx, float x, float y, float z, string deviceName);
        public event CreateStorageDeviceHandler? OnCreateStorageDevice;

        public void CreateStorageDevice(float x, float y, float z, string deviceName)
        {
            conn.InternalCallReducer(new Reducer.CreateStorageDevice(x, y, z, deviceName), this.SetCallReducerFlags.CreateStorageDeviceFlags);
        }

        public bool InvokeCreateStorageDevice(ReducerEventContext ctx, Reducer.CreateStorageDevice args)
        {
            if (OnCreateStorageDevice == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCreateStorageDevice(
                ctx,
                args.X,
                args.Y,
                args.Z,
                args.DeviceName
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CreateStorageDevice : Reducer, IReducerArgs
        {
            [DataMember(Name = "x")]
            public float X;
            [DataMember(Name = "y")]
            public float Y;
            [DataMember(Name = "z")]
            public float Z;
            [DataMember(Name = "device_name")]
            public string DeviceName;

            public CreateStorageDevice(
                float X,
                float Y,
                float Z,
                string DeviceName
            )
            {
                this.X = X;
                this.Y = Y;
                this.Z = Z;
                this.DeviceName = DeviceName;
            }

            public CreateStorageDevice()
            {
                this.DeviceName = "";
            }

            string IReducerArgs.ReducerName => "create_storage_device";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags CreateStorageDeviceFlags;
        public void CreateStorageDevice(CallReducerFlags flags) => CreateStorageDeviceFlags = flags;
    }
}
