// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CreateEnergySpireHandler(ReducerEventContext ctx, int worldX, int worldY, int worldZ, float posX, float posY, float posZ, string direction);
        public event CreateEnergySpireHandler? OnCreateEnergySpire;

        public void CreateEnergySpire(int worldX, int worldY, int worldZ, float posX, float posY, float posZ, string direction)
        {
            conn.InternalCallReducer(new Reducer.CreateEnergySpire(worldX, worldY, worldZ, posX, posY, posZ, direction), this.SetCallReducerFlags.CreateEnergySpireFlags);
        }

        public bool InvokeCreateEnergySpire(ReducerEventContext ctx, Reducer.CreateEnergySpire args)
        {
            if (OnCreateEnergySpire == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCreateEnergySpire(
                ctx,
                args.WorldX,
                args.WorldY,
                args.WorldZ,
                args.PosX,
                args.PosY,
                args.PosZ,
                args.Direction
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CreateEnergySpire : Reducer, IReducerArgs
        {
            [DataMember(Name = "world_x")]
            public int WorldX;
            [DataMember(Name = "world_y")]
            public int WorldY;
            [DataMember(Name = "world_z")]
            public int WorldZ;
            [DataMember(Name = "pos_x")]
            public float PosX;
            [DataMember(Name = "pos_y")]
            public float PosY;
            [DataMember(Name = "pos_z")]
            public float PosZ;
            [DataMember(Name = "direction")]
            public string Direction;

            public CreateEnergySpire(
                int WorldX,
                int WorldY,
                int WorldZ,
                float PosX,
                float PosY,
                float PosZ,
                string Direction
            )
            {
                this.WorldX = WorldX;
                this.WorldY = WorldY;
                this.WorldZ = WorldZ;
                this.PosX = PosX;
                this.PosY = PosY;
                this.PosZ = PosZ;
                this.Direction = Direction;
            }

            public CreateEnergySpire()
            {
                this.Direction = "";
            }

            string IReducerArgs.ReducerName => "create_energy_spire";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags CreateEnergySpireFlags;
        public void CreateEnergySpire(CallReducerFlags flags) => CreateEnergySpireFlags = flags;
    }
}
