// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DebugResetSpawnPositionHandler(ReducerEventContext ctx);
        public event DebugResetSpawnPositionHandler? OnDebugResetSpawnPosition;

        public void DebugResetSpawnPosition()
        {
            conn.InternalCallReducer(new Reducer.DebugResetSpawnPosition(), this.SetCallReducerFlags.DebugResetSpawnPositionFlags);
        }

        public bool InvokeDebugResetSpawnPosition(ReducerEventContext ctx, Reducer.DebugResetSpawnPosition args)
        {
            if (OnDebugResetSpawnPosition == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDebugResetSpawnPosition(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DebugResetSpawnPosition : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "debug_reset_spawn_position";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags DebugResetSpawnPositionFlags;
        public void DebugResetSpawnPosition(CallReducerFlags flags) => DebugResetSpawnPositionFlags = flags;
    }
}
