// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void EnsurePlayerInventoryHandler(ReducerEventContext ctx);
        public event EnsurePlayerInventoryHandler? OnEnsurePlayerInventory;

        public void EnsurePlayerInventory()
        {
            conn.InternalCallReducer(new Reducer.EnsurePlayerInventory(), this.SetCallReducerFlags.EnsurePlayerInventoryFlags);
        }

        public bool InvokeEnsurePlayerInventory(ReducerEventContext ctx, Reducer.EnsurePlayerInventory args)
        {
            if (OnEnsurePlayerInventory == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnEnsurePlayerInventory(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class EnsurePlayerInventory : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "ensure_player_inventory";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags EnsurePlayerInventoryFlags;
        public void EnsurePlayerInventory(CallReducerFlags flags) => EnsurePlayerInventoryFlags = flags;
    }
}
