// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ListActiveMiningHandler(ReducerEventContext ctx);
        public event ListActiveMiningHandler? OnListActiveMining;

        public void ListActiveMining()
        {
            conn.InternalCallReducer(new Reducer.ListActiveMining(), this.SetCallReducerFlags.ListActiveMiningFlags);
        }

        public bool InvokeListActiveMining(ReducerEventContext ctx, Reducer.ListActiveMining args)
        {
            if (OnListActiveMining == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnListActiveMining(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ListActiveMining : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "list_active_mining";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ListActiveMiningFlags;
        public void ListActiveMining(CallReducerFlags flags) => ListActiveMiningFlags = flags;
    }
}
