// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void LoginWithSessionHandler(ReducerEventContext ctx, string username, string pin, string deviceInfo);
        public event LoginWithSessionHandler? OnLoginWithSession;

        public void LoginWithSession(string username, string pin, string deviceInfo)
        {
            conn.InternalCallReducer(new Reducer.LoginWithSession(username, pin, deviceInfo), this.SetCallReducerFlags.LoginWithSessionFlags);
        }

        public bool InvokeLoginWithSession(ReducerEventContext ctx, Reducer.LoginWithSession args)
        {
            if (OnLoginWithSession == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnLoginWithSession(
                ctx,
                args.Username,
                args.Pin,
                args.DeviceInfo
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class LoginWithSession : Reducer, IReducerArgs
        {
            [DataMember(Name = "username")]
            public string Username;
            [DataMember(Name = "pin")]
            public string Pin;
            [DataMember(Name = "device_info")]
            public string DeviceInfo;

            public LoginWithSession(
                string Username,
                string Pin,
                string DeviceInfo
            )
            {
                this.Username = Username;
                this.Pin = Pin;
                this.DeviceInfo = DeviceInfo;
            }

            public LoginWithSession()
            {
                this.Username = "";
                this.Pin = "";
                this.DeviceInfo = "";
            }

            string IReducerArgs.ReducerName => "login_with_session";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags LoginWithSessionFlags;
        public void LoginWithSession(CallReducerFlags flags) => LoginWithSessionFlags = flags;
    }
}
