// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SetOrbPacketsHandler(ReducerEventContext ctx, ulong sourceId, uint newCount);
        public event SetOrbPacketsHandler? OnSetOrbPackets;

        public void SetOrbPackets(ulong sourceId, uint newCount)
        {
            conn.InternalCallReducer(new Reducer.SetOrbPackets(sourceId, newCount), this.SetCallReducerFlags.SetOrbPacketsFlags);
        }

        public bool InvokeSetOrbPackets(ReducerEventContext ctx, Reducer.SetOrbPackets args)
        {
            if (OnSetOrbPackets == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSetOrbPackets(
                ctx,
                args.SourceId,
                args.NewCount
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SetOrbPackets : Reducer, IReducerArgs
        {
            [DataMember(Name = "source_id")]
            public ulong SourceId;
            [DataMember(Name = "new_count")]
            public uint NewCount;

            public SetOrbPackets(
                ulong SourceId,
                uint NewCount
            )
            {
                this.SourceId = SourceId;
                this.NewCount = NewCount;
            }

            public SetOrbPackets()
            {
            }

            string IReducerArgs.ReducerName => "set_orb_packets";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags SetOrbPacketsFlags;
        public void SetOrbPackets(CallReducerFlags flags) => SetOrbPacketsFlags = flags;
    }
}
