// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SpawnMixedOrbHandler(ReducerEventContext ctx, float x, float y, float z, uint redPackets, uint greenPackets, uint bluePackets);
        public event SpawnMixedOrbHandler? OnSpawnMixedOrb;

        public void SpawnMixedOrb(float x, float y, float z, uint redPackets, uint greenPackets, uint bluePackets)
        {
            conn.InternalCallReducer(new Reducer.SpawnMixedOrb(x, y, z, redPackets, greenPackets, bluePackets), this.SetCallReducerFlags.SpawnMixedOrbFlags);
        }

        public bool InvokeSpawnMixedOrb(ReducerEventContext ctx, Reducer.SpawnMixedOrb args)
        {
            if (OnSpawnMixedOrb == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSpawnMixedOrb(
                ctx,
                args.X,
                args.Y,
                args.Z,
                args.RedPackets,
                args.GreenPackets,
                args.BluePackets
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SpawnMixedOrb : Reducer, IReducerArgs
        {
            [DataMember(Name = "x")]
            public float X;
            [DataMember(Name = "y")]
            public float Y;
            [DataMember(Name = "z")]
            public float Z;
            [DataMember(Name = "red_packets")]
            public uint RedPackets;
            [DataMember(Name = "green_packets")]
            public uint GreenPackets;
            [DataMember(Name = "blue_packets")]
            public uint BluePackets;

            public SpawnMixedOrb(
                float X,
                float Y,
                float Z,
                uint RedPackets,
                uint GreenPackets,
                uint BluePackets
            )
            {
                this.X = X;
                this.Y = Y;
                this.Z = Z;
                this.RedPackets = RedPackets;
                this.GreenPackets = GreenPackets;
                this.BluePackets = BluePackets;
            }

            public SpawnMixedOrb()
            {
            }

            string IReducerArgs.ReducerName => "spawn_mixed_orb";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags SpawnMixedOrbFlags;
        public void SpawnMixedOrb(CallReducerFlags flags) => SpawnMixedOrbFlags = flags;
    }
}
