// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SpawnAll26SpiresHandler(ReducerEventContext ctx, int worldX, int worldY, int worldZ);
        public event SpawnAll26SpiresHandler? OnSpawnAll26Spires;

        public void SpawnAll26Spires(int worldX, int worldY, int worldZ)
        {
            conn.InternalCallReducer(new Reducer.SpawnAll26Spires(worldX, worldY, worldZ), this.SetCallReducerFlags.SpawnAll26SpiresFlags);
        }

        public bool InvokeSpawnAll26Spires(ReducerEventContext ctx, Reducer.SpawnAll26Spires args)
        {
            if (OnSpawnAll26Spires == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSpawnAll26Spires(
                ctx,
                args.WorldX,
                args.WorldY,
                args.WorldZ
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SpawnAll26Spires : Reducer, IReducerArgs
        {
            [DataMember(Name = "world_x")]
            public int WorldX;
            [DataMember(Name = "world_y")]
            public int WorldY;
            [DataMember(Name = "world_z")]
            public int WorldZ;

            public SpawnAll26Spires(
                int WorldX,
                int WorldY,
                int WorldZ
            )
            {
                this.WorldX = WorldX;
                this.WorldY = WorldY;
                this.WorldZ = WorldZ;
            }

            public SpawnAll26Spires()
            {
            }

            string IReducerArgs.ReducerName => "spawn_all_26_spires";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags SpawnAll26SpiresFlags;
        public void SpawnAll26Spires(CallReducerFlags flags) => SpawnAll26SpiresFlags = flags;
    }
}
