// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SpawnFullSpectrumOrbHandler(ReducerEventContext ctx, float x, float y, float z, uint redPackets, uint yellowPackets, uint greenPackets, uint cyanPackets, uint bluePackets, uint magentaPackets);
        public event SpawnFullSpectrumOrbHandler? OnSpawnFullSpectrumOrb;

        public void SpawnFullSpectrumOrb(float x, float y, float z, uint redPackets, uint yellowPackets, uint greenPackets, uint cyanPackets, uint bluePackets, uint magentaPackets)
        {
            conn.InternalCallReducer(new Reducer.SpawnFullSpectrumOrb(x, y, z, redPackets, yellowPackets, greenPackets, cyanPackets, bluePackets, magentaPackets), this.SetCallReducerFlags.SpawnFullSpectrumOrbFlags);
        }

        public bool InvokeSpawnFullSpectrumOrb(ReducerEventContext ctx, Reducer.SpawnFullSpectrumOrb args)
        {
            if (OnSpawnFullSpectrumOrb == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSpawnFullSpectrumOrb(
                ctx,
                args.X,
                args.Y,
                args.Z,
                args.RedPackets,
                args.YellowPackets,
                args.GreenPackets,
                args.CyanPackets,
                args.BluePackets,
                args.MagentaPackets
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SpawnFullSpectrumOrb : Reducer, IReducerArgs
        {
            [DataMember(Name = "x")]
            public float X;
            [DataMember(Name = "y")]
            public float Y;
            [DataMember(Name = "z")]
            public float Z;
            [DataMember(Name = "red_packets")]
            public uint RedPackets;
            [DataMember(Name = "yellow_packets")]
            public uint YellowPackets;
            [DataMember(Name = "green_packets")]
            public uint GreenPackets;
            [DataMember(Name = "cyan_packets")]
            public uint CyanPackets;
            [DataMember(Name = "blue_packets")]
            public uint BluePackets;
            [DataMember(Name = "magenta_packets")]
            public uint MagentaPackets;

            public SpawnFullSpectrumOrb(
                float X,
                float Y,
                float Z,
                uint RedPackets,
                uint YellowPackets,
                uint GreenPackets,
                uint CyanPackets,
                uint BluePackets,
                uint MagentaPackets
            )
            {
                this.X = X;
                this.Y = Y;
                this.Z = Z;
                this.RedPackets = RedPackets;
                this.YellowPackets = YellowPackets;
                this.GreenPackets = GreenPackets;
                this.CyanPackets = CyanPackets;
                this.BluePackets = BluePackets;
                this.MagentaPackets = MagentaPackets;
            }

            public SpawnFullSpectrumOrb()
            {
            }

            string IReducerArgs.ReducerName => "spawn_full_spectrum_orb";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags SpawnFullSpectrumOrbFlags;
        public void SpawnFullSpectrumOrb(CallReducerFlags flags) => SpawnFullSpectrumOrbFlags = flags;
    }
}
