// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SpawnDebugOrbsHandler(ReducerEventContext ctx, string playerName, uint orbCount, float heightFromSurface, uint red, uint yellow, uint green, uint cyan, uint blue, uint magenta);
        public event SpawnDebugOrbsHandler? OnSpawnDebugOrbs;

        public void SpawnDebugOrbs(string playerName, uint orbCount, float heightFromSurface, uint red, uint yellow, uint green, uint cyan, uint blue, uint magenta)
        {
            conn.InternalCallReducer(new Reducer.SpawnDebugOrbs(playerName, orbCount, heightFromSurface, red, yellow, green, cyan, blue, magenta), this.SetCallReducerFlags.SpawnDebugOrbsFlags);
        }

        public bool InvokeSpawnDebugOrbs(ReducerEventContext ctx, Reducer.SpawnDebugOrbs args)
        {
            if (OnSpawnDebugOrbs == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSpawnDebugOrbs(
                ctx,
                args.PlayerName,
                args.OrbCount,
                args.HeightFromSurface,
                args.Red,
                args.Yellow,
                args.Green,
                args.Cyan,
                args.Blue,
                args.Magenta
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SpawnDebugOrbs : Reducer, IReducerArgs
        {
            [DataMember(Name = "player_name")]
            public string PlayerName;
            [DataMember(Name = "orb_count")]
            public uint OrbCount;
            [DataMember(Name = "height_from_surface")]
            public float HeightFromSurface;
            [DataMember(Name = "red")]
            public uint Red;
            [DataMember(Name = "yellow")]
            public uint Yellow;
            [DataMember(Name = "green")]
            public uint Green;
            [DataMember(Name = "cyan")]
            public uint Cyan;
            [DataMember(Name = "blue")]
            public uint Blue;
            [DataMember(Name = "magenta")]
            public uint Magenta;

            public SpawnDebugOrbs(
                string PlayerName,
                uint OrbCount,
                float HeightFromSurface,
                uint Red,
                uint Yellow,
                uint Green,
                uint Cyan,
                uint Blue,
                uint Magenta
            )
            {
                this.PlayerName = PlayerName;
                this.OrbCount = OrbCount;
                this.HeightFromSurface = HeightFromSurface;
                this.Red = Red;
                this.Yellow = Yellow;
                this.Green = Green;
                this.Cyan = Cyan;
                this.Blue = Blue;
                this.Magenta = Magenta;
            }

            public SpawnDebugOrbs()
            {
                this.PlayerName = "";
            }

            string IReducerArgs.ReducerName => "spawn_debug_orbs";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags SpawnDebugOrbsFlags;
        public void SpawnDebugOrbs(CallReducerFlags flags) => SpawnDebugOrbsFlags = flags;
    }
}
