// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void StopMiningV2Handler(ReducerEventContext ctx, ulong sessionId);
        public event StopMiningV2Handler? OnStopMiningV2;

        public void StopMiningV2(ulong sessionId)
        {
            conn.InternalCallReducer(new Reducer.StopMiningV2(sessionId), this.SetCallReducerFlags.StopMiningV2Flags);
        }

        public bool InvokeStopMiningV2(ReducerEventContext ctx, Reducer.StopMiningV2 args)
        {
            if (OnStopMiningV2 == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnStopMiningV2(
                ctx,
                args.SessionId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class StopMiningV2 : Reducer, IReducerArgs
        {
            [DataMember(Name = "session_id")]
            public ulong SessionId;

            public StopMiningV2(ulong SessionId)
            {
                this.SessionId = SessionId;
            }

            public StopMiningV2()
            {
            }

            string IReducerArgs.ReducerName => "stop_mining_v2";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags StopMiningV2Flags;
        public void StopMiningV2(CallReducerFlags flags) => StopMiningV2Flags = flags;
    }
}
