// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void TickHandler(ReducerEventContext ctx);
        public event TickHandler? OnTick;

        public void Tick()
        {
            conn.InternalCallReducer(new Reducer.Tick(), this.SetCallReducerFlags.TickFlags);
        }

        public bool InvokeTick(ReducerEventContext ctx, Reducer.Tick args)
        {
            if (OnTick == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnTick(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class Tick : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "tick";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags TickFlags;
        public void Tick(CallReducerFlags flags) => TickFlags = flags;
    }
}
