// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void TickPlayerTransfersHandler(ReducerEventContext ctx);
        public event TickPlayerTransfersHandler? OnTickPlayerTransfers;

        public void TickPlayerTransfers()
        {
            conn.InternalCallReducer(new Reducer.TickPlayerTransfers(), this.SetCallReducerFlags.TickPlayerTransfersFlags);
        }

        public bool InvokeTickPlayerTransfers(ReducerEventContext ctx, Reducer.TickPlayerTransfers args)
        {
            if (OnTickPlayerTransfers == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnTickPlayerTransfers(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class TickPlayerTransfers : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "tick_player_transfers";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags TickPlayerTransfersFlags;
        public void TickPlayerTransfers(CallReducerFlags flags) => TickPlayerTransfersFlags = flags;
    }
}
