// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void TravelToWorldHandler(ReducerEventContext ctx, WorldCoords worldCoords);
        public event TravelToWorldHandler? OnTravelToWorld;

        public void TravelToWorld(WorldCoords worldCoords)
        {
            conn.InternalCallReducer(new Reducer.TravelToWorld(worldCoords), this.SetCallReducerFlags.TravelToWorldFlags);
        }

        public bool InvokeTravelToWorld(ReducerEventContext ctx, Reducer.TravelToWorld args)
        {
            if (OnTravelToWorld == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnTravelToWorld(
                ctx,
                args.WorldCoords
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class TravelToWorld : Reducer, IReducerArgs
        {
            [DataMember(Name = "world_coords")]
            public WorldCoords WorldCoords;

            public TravelToWorld(WorldCoords WorldCoords)
            {
                this.WorldCoords = WorldCoords;
            }

            public TravelToWorld()
            {
                this.WorldCoords = new();
            }

            string IReducerArgs.ReducerName => "travel_to_world";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags TravelToWorldFlags;
        public void TravelToWorld(CallReducerFlags flags) => TravelToWorldFlags = flags;
    }
}
