// Client-side frequency band enum for visualization
// This replaces the autogenerated FrequencyBand.g.cs which was removed from server

using System;

namespace SpacetimeDB.Types
{
    /// <summary>
    /// Frequency bands for wave packet visualization (client-side only).
    /// Maps to the 6 primary frequencies used in the game.
    /// </summary>
    [Serializable]
    public enum FrequencyBand
    {
        Red = 0,      // 0° (frequency 0.0)
        Yellow = 1,   // 60° (frequency ~1/6)
        Green = 2,    // 120° (frequency ~1/3)
        Cyan = 3,     // 180° (frequency ~1/2)
        Blue = 4,     // 240° (frequency ~2/3)
        Magenta = 5   // 300° (frequency ~5/6)
    }
}
