// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class AccountIdentityHandle : RemoteTableHandle<EventContext, AccountIdentity>
        {
            protected override string RemoteTableName => "account_identity";

            public sealed class IdentityUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(AccountIdentity row) => row.Identity;

                public IdentityUniqueIndex(AccountIdentityHandle table) : base(table) { }
            }

            public readonly IdentityUniqueIndex Identity;

            internal AccountIdentityHandle(DbConnection conn) : base(conn)
            {
                Identity = new(this);
            }

            protected override object GetPrimaryKey(AccountIdentity row) => row.Identity;
        }

        public readonly AccountIdentityHandle AccountIdentity;
    }
}
