// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class AccountIdentityHandle : RemoteTableHandle<EventContext, AccountIdentity>
        {
            protected override string RemoteTableName => "account_identity";

            public sealed class AccountIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(AccountIdentity row) => row.AccountId;

                public AccountIdUniqueIndex(AccountIdentityHandle table) : base(table) { }
            }

            public readonly AccountIdUniqueIndex AccountId;

            internal AccountIdentityHandle(DbConnection conn) : base(conn)
            {
                AccountId = new(this);
            }

            protected override object GetPrimaryKey(AccountIdentity row) => row.AccountId;
        }

        public readonly AccountIdentityHandle AccountIdentity;
    }
}
