// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class BroadcastMessageHandle : RemoteTableHandle<EventContext, BroadcastMessage>
        {
            protected override string RemoteTableName => "broadcast_message";

            public sealed class MessageIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(BroadcastMessage row) => row.MessageId;

                public MessageIdUniqueIndex(BroadcastMessageHandle table) : base(table) { }
            }

            public readonly MessageIdUniqueIndex MessageId;

            internal BroadcastMessageHandle(DbConnection conn) : base(conn)
            {
                MessageId = new(this);
            }

            protected override object GetPrimaryKey(BroadcastMessage row) => row.MessageId;
        }

        public readonly BroadcastMessageHandle BroadcastMessage;
    }
}
