// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class DeviceConnectionHandle : RemoteTableHandle<EventContext, DeviceConnection>
        {
            protected override string RemoteTableName => "device_connection";

            public sealed class ConnectionIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(DeviceConnection row) => row.ConnectionId;

                public ConnectionIdUniqueIndex(DeviceConnectionHandle table) : base(table) { }
            }

            public readonly ConnectionIdUniqueIndex ConnectionId;

            internal DeviceConnectionHandle(DbConnection conn) : base(conn)
            {
                ConnectionId = new(this);
            }

            protected override object GetPrimaryKey(DeviceConnection row) => row.ConnectionId;
        }

        public readonly DeviceConnectionHandle DeviceConnection;
    }
}
