// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EnergySpireHandle : RemoteTableHandle<EventContext, EnergySpire>
        {
            protected override string RemoteTableName => "energy_spire";

            public sealed class SpireIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(EnergySpire row) => row.SpireId;

                public SpireIdUniqueIndex(EnergySpireHandle table) : base(table) { }
            }

            public readonly SpireIdUniqueIndex SpireId;

            internal EnergySpireHandle(DbConnection conn) : base(conn)
            {
                SpireId = new(this);
            }

            protected override object GetPrimaryKey(EnergySpire row) => row.SpireId;
        }

        public readonly EnergySpireHandle EnergySpire;
    }
}
