// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EnergyTransferHandle : RemoteTableHandle<EventContext, EnergyTransfer>
        {
            protected override string RemoteTableName => "energy_transfer";

            public sealed class TransferIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(EnergyTransfer row) => row.TransferId;

                public TransferIdUniqueIndex(EnergyTransferHandle table) : base(table) { }
            }

            public readonly TransferIdUniqueIndex TransferId;

            internal EnergyTransferHandle(DbConnection conn) : base(conn)
            {
                TransferId = new(this);
            }

            protected override object GetPrimaryKey(EnergyTransfer row) => row.TransferId;
        }

        public readonly EnergyTransferHandle EnergyTransfer;
    }
}
