// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EnergyPuddleHandle : RemoteTableHandle<EventContext, EnergyPuddle>
        {
            protected override string RemoteTableName => "energy_puddle";

            public sealed class PuddleIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(EnergyPuddle row) => row.PuddleId;

                public PuddleIdUniqueIndex(EnergyPuddleHandle table) : base(table) { }
            }

            public readonly PuddleIdUniqueIndex PuddleId;

            internal EnergyPuddleHandle(DbConnection conn) : base(conn)
            {
                PuddleId = new(this);
            }

            protected override object GetPrimaryKey(EnergyPuddle row) => row.PuddleId;
        }

        public readonly EnergyPuddleHandle EnergyPuddle;
    }
}
