// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EnergyOrbHandle : RemoteTableHandle<EventContext, EnergyOrb>
        {
            protected override string RemoteTableName => "energy_orb";

            public sealed class OrbIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(EnergyOrb row) => row.OrbId;

                public OrbIdUniqueIndex(EnergyOrbHandle table) : base(table) { }
            }

            public readonly OrbIdUniqueIndex OrbId;

            internal EnergyOrbHandle(DbConnection conn) : base(conn)
            {
                OrbId = new(this);
            }

            protected override object GetPrimaryKey(EnergyOrb row) => row.OrbId;
        }

        public readonly EnergyOrbHandle EnergyOrb;
    }
}
