// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EnergyStorageHandle : RemoteTableHandle<EventContext, EnergyStorage>
        {
            protected override string RemoteTableName => "energy_storage";

            public sealed class StorageEntryIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(EnergyStorage row) => row.StorageEntryId;

                public StorageEntryIdUniqueIndex(EnergyStorageHandle table) : base(table) { }
            }

            public readonly StorageEntryIdUniqueIndex StorageEntryId;

            internal EnergyStorageHandle(DbConnection conn) : base(conn)
            {
                StorageEntryId = new(this);
            }

            protected override object GetPrimaryKey(EnergyStorage row) => row.StorageEntryId;
        }

        public readonly EnergyStorageHandle EnergyStorage;
    }
}
