// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class GameSettingsHandle : RemoteTableHandle<EventContext, GameSettings>
        {
            protected override string RemoteTableName => "game_settings";

            public sealed class SettingKeyUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(GameSettings row) => row.SettingKey;

                public SettingKeyUniqueIndex(GameSettingsHandle table) : base(table) { }
            }

            public readonly SettingKeyUniqueIndex SettingKey;

            internal GameSettingsHandle(DbConnection conn) : base(conn)
            {
                SettingKey = new(this);
            }

            protected override object GetPrimaryKey(GameSettings row) => row.SettingKey;
        }

        public readonly GameSettingsHandle GameSettings;
    }
}
