// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class GameSettingsHandle : RemoteTableHandle<EventContext, GameSettings>
        {
            protected override string RemoteTableName => "game_settings";

            public sealed class IdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(GameSettings row) => row.Id;

                public IdUniqueIndex(GameSettingsHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal GameSettingsHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(GameSettings row) => row.Id;
        }

        public readonly GameSettingsHandle GameSettings;
    }
}
