// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class MinerDeviceHandle : RemoteTableHandle<EventContext, MinerDevice>
        {
            protected override string RemoteTableName => "miner_device";

            public sealed class MinerIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(MinerDevice row) => row.MinerId;

                public MinerIdUniqueIndex(MinerDeviceHandle table) : base(table) { }
            }

            public readonly MinerIdUniqueIndex MinerId;

            internal MinerDeviceHandle(DbConnection conn) : base(conn)
            {
                MinerId = new(this);
            }

            protected override object GetPrimaryKey(MinerDevice row) => row.MinerId;
        }

        public readonly MinerDeviceHandle MinerDevice;
    }
}
