// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerChatMessageHandle : RemoteTableHandle<EventContext, PlayerChatMessage>
        {
            protected override string RemoteTableName => "player_chat_message";

            public sealed class MessageIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PlayerChatMessage row) => row.MessageId;

                public MessageIdUniqueIndex(PlayerChatMessageHandle table) : base(table) { }
            }

            public readonly MessageIdUniqueIndex MessageId;

            internal PlayerChatMessageHandle(DbConnection conn) : base(conn)
            {
                MessageId = new(this);
            }

            protected override object GetPrimaryKey(PlayerChatMessage row) => row.MessageId;
        }

        public readonly PlayerChatMessageHandle PlayerChatMessage;
    }
}
