// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerSessionHandle : RemoteTableHandle<EventContext, PlayerSession>
        {
            protected override string RemoteTableName => "player_session";

            public sealed class SessionIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PlayerSession row) => row.SessionId;

                public SessionIdUniqueIndex(PlayerSessionHandle table) : base(table) { }
            }

            public readonly SessionIdUniqueIndex SessionId;

            internal PlayerSessionHandle(DbConnection conn) : base(conn)
            {
                SessionId = new(this);
            }

            protected override object GetPrimaryKey(PlayerSession row) => row.SessionId;
        }

        public readonly PlayerSessionHandle PlayerSession;
    }
}
