// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class QuantaOrbHandle : RemoteTableHandle<EventContext, QuantaOrb>
        {
            protected override string RemoteTableName => "quanta_orb";

            public sealed class OrbIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(QuantaOrb row) => row.OrbId;

                public OrbIdUniqueIndex(QuantaOrbHandle table) : base(table) { }
            }

            public readonly OrbIdUniqueIndex OrbId;

            internal QuantaOrbHandle(DbConnection conn) : base(conn)
            {
                OrbId = new(this);
            }

            protected override object GetPrimaryKey(QuantaOrb row) => row.OrbId;
        }

        public readonly QuantaOrbHandle QuantaOrb;
    }
}
