// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class QuantumTunnelHandle : RemoteTableHandle<EventContext, QuantumTunnel>
        {
            protected override string RemoteTableName => "quantum_tunnel";

            public sealed class TunnelIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(QuantumTunnel row) => row.TunnelId;

                public TunnelIdUniqueIndex(QuantumTunnelHandle table) : base(table) { }
            }

            public readonly TunnelIdUniqueIndex TunnelId;

            internal QuantumTunnelHandle(DbConnection conn) : base(conn)
            {
                TunnelId = new(this);
            }

            protected override object GetPrimaryKey(QuantumTunnel row) => row.TunnelId;
        }

        public readonly QuantumTunnelHandle QuantumTunnel;
    }
}
