// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class QuantaStorageHandle : RemoteTableHandle<EventContext, QuantaStorage>
        {
            protected override string RemoteTableName => "quanta_storage";

            public sealed class StorageIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(QuantaStorage row) => row.StorageId;

                public StorageIdUniqueIndex(QuantaStorageHandle table) : base(table) { }
            }

            public readonly StorageIdUniqueIndex StorageId;

            internal QuantaStorageHandle(DbConnection conn) : base(conn)
            {
                StorageId = new(this);
            }

            protected override object GetPrimaryKey(QuantaStorage row) => row.StorageId;
        }

        public readonly QuantaStorageHandle QuantaStorage;
    }
}
