// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class SessionResultHandle : RemoteTableHandle<EventContext, SessionResult>
        {
            protected override string RemoteTableName => "session_result";

            public sealed class IdentityUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(SessionResult row) => row.Identity;

                public IdentityUniqueIndex(SessionResultHandle table) : base(table) { }
            }

            public readonly IdentityUniqueIndex Identity;

            internal SessionResultHandle(DbConnection conn) : base(conn)
            {
                Identity = new(this);
            }

            protected override object GetPrimaryKey(SessionResult row) => row.Identity;
        }

        public readonly SessionResultHandle SessionResult;
    }
}
