// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class SimpleEnergyStorageHandle : RemoteTableHandle<EventContext, SimpleEnergyStorage>
        {
            protected override string RemoteTableName => "simple_energy_storage";

            public sealed class StorageIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(SimpleEnergyStorage row) => row.StorageId;

                public StorageIdUniqueIndex(SimpleEnergyStorageHandle table) : base(table) { }
            }

            public readonly StorageIdUniqueIndex StorageId;

            internal SimpleEnergyStorageHandle(DbConnection conn) : base(conn)
            {
                StorageId = new(this);
            }

            protected override object GetPrimaryKey(SimpleEnergyStorage row) => row.StorageId;
        }

        public readonly SimpleEnergyStorageHandle SimpleEnergyStorage;
    }
}
