// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class StorageDeviceHandle : RemoteTableHandle<EventContext, StorageDevice>
        {
            protected override string RemoteTableName => "storage_device";

            public sealed class StorageIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(StorageDevice row) => row.StorageId;

                public StorageIdUniqueIndex(StorageDeviceHandle table) : base(table) { }
            }

            public readonly StorageIdUniqueIndex StorageId;

            internal StorageDeviceHandle(DbConnection conn) : base(conn)
            {
                StorageId = new(this);
            }

            protected override object GetPrimaryKey(StorageDevice row) => row.StorageId;
        }

        public readonly StorageDeviceHandle StorageDevice;
    }
}
