// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class TunnelHandle : RemoteTableHandle<EventContext, Tunnel>
        {
            protected override string RemoteTableName => "tunnel";

            public sealed class TunnelIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Tunnel row) => row.TunnelId;

                public TunnelIdUniqueIndex(TunnelHandle table) : base(table) { }
            }

            public readonly TunnelIdUniqueIndex TunnelId;

            internal TunnelHandle(DbConnection conn) : base(conn)
            {
                TunnelId = new(this);
            }

            protected override object GetPrimaryKey(Tunnel row) => row.TunnelId;
        }

        public readonly TunnelHandle Tunnel;
    }
}
