// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class UserAccountHandle : RemoteTableHandle<EventContext, UserAccount>
        {
            protected override string RemoteTableName => "user_account";

            public sealed class AccountIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(UserAccount row) => row.AccountId;

                public AccountIdUniqueIndex(UserAccountHandle table) : base(table) { }
            }

            public readonly AccountIdUniqueIndex AccountId;

            public sealed class UsernameUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(UserAccount row) => row.Username;

                public UsernameUniqueIndex(UserAccountHandle table) : base(table) { }
            }

            public readonly UsernameUniqueIndex Username;

            internal UserAccountHandle(DbConnection conn) : base(conn)
            {
                AccountId = new(this);
                Username = new(this);
            }

            protected override object GetPrimaryKey(UserAccount row) => row.AccountId;
        }

        public readonly UserAccountHandle UserAccount;
    }
}
