// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class WavePacketExtractionHandle : RemoteTableHandle<EventContext, WavePacketExtraction>
        {
            protected override string RemoteTableName => "wave_packet_extraction";

            public sealed class ExtractionIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(WavePacketExtraction row) => row.ExtractionId;

                public ExtractionIdUniqueIndex(WavePacketExtractionHandle table) : base(table) { }
            }

            public readonly ExtractionIdUniqueIndex ExtractionId;

            internal WavePacketExtractionHandle(DbConnection conn) : base(conn)
            {
                ExtractionId = new(this);
            }

            protected override object GetPrimaryKey(WavePacketExtraction row) => row.ExtractionId;
        }

        public readonly WavePacketExtractionHandle WavePacketExtraction;
    }
}
