// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class WavePacketStorageHandle : RemoteTableHandle<EventContext, WavePacketStorage>
        {
            protected override string RemoteTableName => "wave_packet_storage";

            public sealed class StorageIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(WavePacketStorage row) => row.StorageId;

                public StorageIdUniqueIndex(WavePacketStorageHandle table) : base(table) { }
            }

            public readonly StorageIdUniqueIndex StorageId;

            internal WavePacketStorageHandle(DbConnection conn) : base(conn)
            {
                StorageId = new(this);
            }

            protected override object GetPrimaryKey(WavePacketStorage row) => row.StorageId;
        }

        public readonly WavePacketStorageHandle WavePacketStorage;
    }
}
