// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class WavePacketOrbHandle : RemoteTableHandle<EventContext, WavePacketOrb>
        {
            protected override string RemoteTableName => "wave_packet_orb";

            public sealed class OrbIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(WavePacketOrb row) => row.OrbId;

                public OrbIdUniqueIndex(WavePacketOrbHandle table) : base(table) { }
            }

            public readonly OrbIdUniqueIndex OrbId;

            internal WavePacketOrbHandle(DbConnection conn) : base(conn)
            {
                OrbId = new(this);
            }

            protected override object GetPrimaryKey(WavePacketOrb row) => row.OrbId;
        }

        public readonly WavePacketOrbHandle WavePacketOrb;
    }
}
