// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class WorldHandle : RemoteTableHandle<EventContext, World>
        {
            protected override string RemoteTableName => "world";

            public sealed class WorldCoordsUniqueIndex : UniqueIndexBase<WorldCoords>
            {
                protected override WorldCoords GetKey(World row) => row.WorldCoords;

                public WorldCoordsUniqueIndex(WorldHandle table) : base(table) { }
            }

            public readonly WorldCoordsUniqueIndex WorldCoords;

            internal WorldHandle(DbConnection conn) : base(conn)
            {
                WorldCoords = new(this);
            }

            protected override object GetPrimaryKey(World row) => row.WorldCoords;
        }

        public readonly WorldHandle World;
    }
}
