// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class WorldCircuitHandle : RemoteTableHandle<EventContext, WorldCircuit>
        {
            protected override string RemoteTableName => "world_circuit";

            public sealed class WorldCoordsUniqueIndex : UniqueIndexBase<WorldCoords>
            {
                protected override WorldCoords GetKey(WorldCircuit row) => row.WorldCoords;

                public WorldCoordsUniqueIndex(WorldCircuitHandle table) : base(table) { }
            }

            public readonly WorldCoordsUniqueIndex WorldCoords;

            internal WorldCircuitHandle(DbConnection conn) : base(conn)
            {
                WorldCoords = new(this);
            }

            protected override object GetPrimaryKey(WorldCircuit row) => row.WorldCoords;
        }

        public readonly WorldCircuitHandle WorldCircuit;
    }
}
