// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void BroadcastChatMessageHandler(ReducerEventContext ctx, string content);
        public event BroadcastChatMessageHandler? OnBroadcastChatMessage;

        public void BroadcastChatMessage(string content)
        {
            conn.InternalCallReducer(new Reducer.BroadcastChatMessage(content), this.SetCallReducerFlags.BroadcastChatMessageFlags);
        }

        public bool InvokeBroadcastChatMessage(ReducerEventContext ctx, Reducer.BroadcastChatMessage args)
        {
            if (OnBroadcastChatMessage == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnBroadcastChatMessage(
                ctx,
                args.Content
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class BroadcastChatMessage : Reducer, IReducerArgs
        {
            [DataMember(Name = "content")]
            public string Content;

            public BroadcastChatMessage(string Content)
            {
                this.Content = Content;
            }

            public BroadcastChatMessage()
            {
                this.Content = "";
            }

            string IReducerArgs.ReducerName => "broadcast_chat_message";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags BroadcastChatMessageFlags;
        public void BroadcastChatMessage(CallReducerFlags flags) => BroadcastChatMessageFlags = flags;
    }
}
