// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CaptureWavePacketHandler(ReducerEventContext ctx, ulong wavePacketId);
        public event CaptureWavePacketHandler? OnCaptureWavePacket;

        public void CaptureWavePacket(ulong wavePacketId)
        {
            conn.InternalCallReducer(new Reducer.CaptureWavePacket(wavePacketId), this.SetCallReducerFlags.CaptureWavePacketFlags);
        }

        public bool InvokeCaptureWavePacket(ReducerEventContext ctx, Reducer.CaptureWavePacket args)
        {
            if (OnCaptureWavePacket == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCaptureWavePacket(
                ctx,
                args.WavePacketId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CaptureWavePacket : Reducer, IReducerArgs
        {
            [DataMember(Name = "wave_packet_id")]
            public ulong WavePacketId;

            public CaptureWavePacket(ulong WavePacketId)
            {
                this.WavePacketId = WavePacketId;
            }

            public CaptureWavePacket()
            {
            }

            string IReducerArgs.ReducerName => "capture_wave_packet";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags CaptureWavePacketFlags;
        public void CaptureWavePacket(CallReducerFlags flags) => CaptureWavePacketFlags = flags;
    }
}
