// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ChooseStartingCrystalHandler(ReducerEventContext ctx, CrystalType crystalType);
        public event ChooseStartingCrystalHandler? OnChooseStartingCrystal;

        public void ChooseStartingCrystal(CrystalType crystalType)
        {
            conn.InternalCallReducer(new Reducer.ChooseStartingCrystal(crystalType), this.SetCallReducerFlags.ChooseStartingCrystalFlags);
        }

        public bool InvokeChooseStartingCrystal(ReducerEventContext ctx, Reducer.ChooseStartingCrystal args)
        {
            if (OnChooseStartingCrystal == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnChooseStartingCrystal(
                ctx,
                args.CrystalType
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ChooseStartingCrystal : Reducer, IReducerArgs
        {
            [DataMember(Name = "crystal_type")]
            public CrystalType CrystalType;

            public ChooseStartingCrystal(CrystalType CrystalType)
            {
                this.CrystalType = CrystalType;
            }

            public ChooseStartingCrystal()
            {
            }

            string IReducerArgs.ReducerName => "choose_starting_crystal";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ChooseStartingCrystalFlags;
        public void ChooseStartingCrystal(CallReducerFlags flags) => ChooseStartingCrystalFlags = flags;
    }
}
