// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ChooseCrystalHandler(ReducerEventContext ctx, CrystalType crystalType);
        public event ChooseCrystalHandler? OnChooseCrystal;

        public void ChooseCrystal(CrystalType crystalType)
        {
            conn.InternalCallReducer(new Reducer.ChooseCrystal(crystalType), this.SetCallReducerFlags.ChooseCrystalFlags);
        }

        public bool InvokeChooseCrystal(ReducerEventContext ctx, Reducer.ChooseCrystal args)
        {
            if (OnChooseCrystal == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnChooseCrystal(
                ctx,
                args.CrystalType
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ChooseCrystal : Reducer, IReducerArgs
        {
            [DataMember(Name = "crystal_type")]
            public CrystalType CrystalType;

            public ChooseCrystal(CrystalType CrystalType)
            {
                this.CrystalType = CrystalType;
            }

            public ChooseCrystal()
            {
            }

            string IReducerArgs.ReducerName => "choose_crystal";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ChooseCrystalFlags;
        public void ChooseCrystal(CallReducerFlags flags) => ChooseCrystalFlags = flags;
    }
}
