// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ClearAllSourcesHandler(ReducerEventContext ctx);
        public event ClearAllSourcesHandler? OnClearAllSources;

        public void ClearAllSources()
        {
            conn.InternalCallReducer(new Reducer.ClearAllSources(), this.SetCallReducerFlags.ClearAllSourcesFlags);
        }

        public bool InvokeClearAllSources(ReducerEventContext ctx, Reducer.ClearAllSources args)
        {
            if (OnClearAllSources == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnClearAllSources(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ClearAllSources : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "clear_all_sources";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ClearAllSourcesFlags;
        public void ClearAllSources(CallReducerFlags flags) => ClearAllSourcesFlags = flags;
    }
}
