// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CleanupExpiredSessionsHandler(ReducerEventContext ctx);
        public event CleanupExpiredSessionsHandler? OnCleanupExpiredSessions;

        public void CleanupExpiredSessions()
        {
            conn.InternalCallReducer(new Reducer.CleanupExpiredSessions(), this.SetCallReducerFlags.CleanupExpiredSessionsFlags);
        }

        public bool InvokeCleanupExpiredSessions(ReducerEventContext ctx, Reducer.CleanupExpiredSessions args)
        {
            if (OnCleanupExpiredSessions == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCleanupExpiredSessions(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CleanupExpiredSessions : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "cleanup_expired_sessions";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags CleanupExpiredSessionsFlags;
        public void CleanupExpiredSessions(CallReducerFlags flags) => CleanupExpiredSessionsFlags = flags;
    }
}
