// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ClearSessionResultHandler(ReducerEventContext ctx);
        public event ClearSessionResultHandler? OnClearSessionResult;

        public void ClearSessionResult()
        {
            conn.InternalCallReducer(new Reducer.ClearSessionResult(), this.SetCallReducerFlags.ClearSessionResultFlags);
        }

        public bool InvokeClearSessionResult(ReducerEventContext ctx, Reducer.ClearSessionResult args)
        {
            if (OnClearSessionResult == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnClearSessionResult(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ClearSessionResult : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "clear_session_result";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ClearSessionResultFlags;
        public void ClearSessionResult(CallReducerFlags flags) => ClearSessionResultFlags = flags;
    }
}
