// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CollectQuantaOrbHandler(ReducerEventContext ctx, ulong orbId, ulong playerId);
        public event CollectQuantaOrbHandler? OnCollectQuantaOrb;

        public void CollectQuantaOrb(ulong orbId, ulong playerId)
        {
            conn.InternalCallReducer(new Reducer.CollectQuantaOrb(orbId, playerId), this.SetCallReducerFlags.CollectQuantaOrbFlags);
        }

        public bool InvokeCollectQuantaOrb(ReducerEventContext ctx, Reducer.CollectQuantaOrb args)
        {
            if (OnCollectQuantaOrb == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCollectQuantaOrb(
                ctx,
                args.OrbId,
                args.PlayerId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CollectQuantaOrb : Reducer, IReducerArgs
        {
            [DataMember(Name = "orb_id")]
            public ulong OrbId;
            [DataMember(Name = "player_id")]
            public ulong PlayerId;

            public CollectQuantaOrb(
                ulong OrbId,
                ulong PlayerId
            )
            {
                this.OrbId = OrbId;
                this.PlayerId = PlayerId;
            }

            public CollectQuantaOrb()
            {
            }

            string IReducerArgs.ReducerName => "collect_quanta_orb";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags CollectQuantaOrbFlags;
        public void CollectQuantaOrb(CallReducerFlags flags) => CollectQuantaOrbFlags = flags;
    }
}
