// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CollectSimpleEnergyOrbHandler(ReducerEventContext ctx, ulong orbId, uint collectorPlayerId);
        public event CollectSimpleEnergyOrbHandler? OnCollectSimpleEnergyOrb;

        public void CollectSimpleEnergyOrb(ulong orbId, uint collectorPlayerId)
        {
            conn.InternalCallReducer(new Reducer.CollectSimpleEnergyOrb(orbId, collectorPlayerId), this.SetCallReducerFlags.CollectSimpleEnergyOrbFlags);
        }

        public bool InvokeCollectSimpleEnergyOrb(ReducerEventContext ctx, Reducer.CollectSimpleEnergyOrb args)
        {
            if (OnCollectSimpleEnergyOrb == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCollectSimpleEnergyOrb(
                ctx,
                args.OrbId,
                args.CollectorPlayerId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CollectSimpleEnergyOrb : Reducer, IReducerArgs
        {
            [DataMember(Name = "orb_id")]
            public ulong OrbId;
            [DataMember(Name = "collector_player_id")]
            public uint CollectorPlayerId;

            public CollectSimpleEnergyOrb(
                ulong OrbId,
                uint CollectorPlayerId
            )
            {
                this.OrbId = OrbId;
                this.CollectorPlayerId = CollectorPlayerId;
            }

            public CollectSimpleEnergyOrb()
            {
            }

            string IReducerArgs.ReducerName => "collect_simple_energy_orb";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags CollectSimpleEnergyOrbFlags;
        public void CollectSimpleEnergyOrb(CallReducerFlags flags) => CollectSimpleEnergyOrbFlags = flags;
    }
}
