// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CompleteTransferHandler(ReducerEventContext ctx, ulong transferId);
        public event CompleteTransferHandler? OnCompleteTransfer;

        public void CompleteTransfer(ulong transferId)
        {
            conn.InternalCallReducer(new Reducer.CompleteTransfer(transferId), this.SetCallReducerFlags.CompleteTransferFlags);
        }

        public bool InvokeCompleteTransfer(ReducerEventContext ctx, Reducer.CompleteTransfer args)
        {
            if (OnCompleteTransfer == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCompleteTransfer(
                ctx,
                args.TransferId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CompleteTransfer : Reducer, IReducerArgs
        {
            [DataMember(Name = "transfer_id")]
            public ulong TransferId;

            public CompleteTransfer(ulong TransferId)
            {
                this.TransferId = TransferId;
            }

            public CompleteTransfer()
            {
            }

            string IReducerArgs.ReducerName => "complete_transfer";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags CompleteTransferFlags;
        public void CompleteTransfer(CallReducerFlags flags) => CompleteTransferFlags = flags;
    }
}
