// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DebugSimpleEnergySystemStatusHandler(ReducerEventContext ctx);
        public event DebugSimpleEnergySystemStatusHandler? OnDebugSimpleEnergySystemStatus;

        public void DebugSimpleEnergySystemStatus()
        {
            conn.InternalCallReducer(new Reducer.DebugSimpleEnergySystemStatus(), this.SetCallReducerFlags.DebugSimpleEnergySystemStatusFlags);
        }

        public bool InvokeDebugSimpleEnergySystemStatus(ReducerEventContext ctx, Reducer.DebugSimpleEnergySystemStatus args)
        {
            if (OnDebugSimpleEnergySystemStatus == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDebugSimpleEnergySystemStatus(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DebugSimpleEnergySystemStatus : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "debug_simple_energy_system_status";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags DebugSimpleEnergySystemStatusFlags;
        public void DebugSimpleEnergySystemStatus(CallReducerFlags flags) => DebugSimpleEnergySystemStatusFlags = flags;
    }
}
