// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DebugCompareEnergySystemsHandler(ReducerEventContext ctx);
        public event DebugCompareEnergySystemsHandler? OnDebugCompareEnergySystems;

        public void DebugCompareEnergySystems()
        {
            conn.InternalCallReducer(new Reducer.DebugCompareEnergySystems(), this.SetCallReducerFlags.DebugCompareEnergySystemsFlags);
        }

        public bool InvokeDebugCompareEnergySystems(ReducerEventContext ctx, Reducer.DebugCompareEnergySystems args)
        {
            if (OnDebugCompareEnergySystems == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDebugCompareEnergySystems(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DebugCompareEnergySystems : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "debug_compare_energy_systems";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags DebugCompareEnergySystemsFlags;
        public void DebugCompareEnergySystems(CallReducerFlags flags) => DebugCompareEnergySystemsFlags = flags;
    }
}
