// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DebugResetWorldHandler(ReducerEventContext ctx);
        public event DebugResetWorldHandler? OnDebugResetWorld;

        public void DebugResetWorld()
        {
            conn.InternalCallReducer(new Reducer.DebugResetWorld(), this.SetCallReducerFlags.DebugResetWorldFlags);
        }

        public bool InvokeDebugResetWorld(ReducerEventContext ctx, Reducer.DebugResetWorld args)
        {
            if (OnDebugResetWorld == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDebugResetWorld(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DebugResetWorld : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "debug_reset_world";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags DebugResetWorldFlags;
        public void DebugResetWorld(CallReducerFlags flags) => DebugResetWorldFlags = flags;
    }
}
