// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DebugListExtractionsHandler(ReducerEventContext ctx);
        public event DebugListExtractionsHandler? OnDebugListExtractions;

        public void DebugListExtractions()
        {
            conn.InternalCallReducer(new Reducer.DebugListExtractions(), this.SetCallReducerFlags.DebugListExtractionsFlags);
        }

        public bool InvokeDebugListExtractions(ReducerEventContext ctx, Reducer.DebugListExtractions args)
        {
            if (OnDebugListExtractions == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDebugListExtractions(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DebugListExtractions : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "debug_list_extractions";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags DebugListExtractionsFlags;
        public void DebugListExtractions(CallReducerFlags flags) => DebugListExtractionsFlags = flags;
    }
}
