// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DebugAddTestPacketsHandler(ReducerEventContext ctx, uint red, uint yellow, uint green, uint cyan, uint blue, uint magenta);
        public event DebugAddTestPacketsHandler? OnDebugAddTestPackets;

        public void DebugAddTestPackets(uint red, uint yellow, uint green, uint cyan, uint blue, uint magenta)
        {
            conn.InternalCallReducer(new Reducer.DebugAddTestPackets(red, yellow, green, cyan, blue, magenta), this.SetCallReducerFlags.DebugAddTestPacketsFlags);
        }

        public bool InvokeDebugAddTestPackets(ReducerEventContext ctx, Reducer.DebugAddTestPackets args)
        {
            if (OnDebugAddTestPackets == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDebugAddTestPackets(
                ctx,
                args.Red,
                args.Yellow,
                args.Green,
                args.Cyan,
                args.Blue,
                args.Magenta
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DebugAddTestPackets : Reducer, IReducerArgs
        {
            [DataMember(Name = "red")]
            public uint Red;
            [DataMember(Name = "yellow")]
            public uint Yellow;
            [DataMember(Name = "green")]
            public uint Green;
            [DataMember(Name = "cyan")]
            public uint Cyan;
            [DataMember(Name = "blue")]
            public uint Blue;
            [DataMember(Name = "magenta")]
            public uint Magenta;

            public DebugAddTestPackets(
                uint Red,
                uint Yellow,
                uint Green,
                uint Cyan,
                uint Blue,
                uint Magenta
            )
            {
                this.Red = Red;
                this.Yellow = Yellow;
                this.Green = Green;
                this.Cyan = Cyan;
                this.Blue = Blue;
                this.Magenta = Magenta;
            }

            public DebugAddTestPackets()
            {
            }

            string IReducerArgs.ReducerName => "debug_add_test_packets";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags DebugAddTestPacketsFlags;
        public void DebugAddTestPackets(CallReducerFlags flags) => DebugAddTestPacketsFlags = flags;
    }
}
