// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DebugInitWorldHandler(ReducerEventContext ctx);
        public event DebugInitWorldHandler? OnDebugInitWorld;

        public void DebugInitWorld()
        {
            conn.InternalCallReducer(new Reducer.DebugInitWorld(), this.SetCallReducerFlags.DebugInitWorldFlags);
        }

        public bool InvokeDebugInitWorld(ReducerEventContext ctx, Reducer.DebugInitWorld args)
        {
            if (OnDebugInitWorld == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDebugInitWorld(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DebugInitWorld : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "debug_init_world";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags DebugInitWorldFlags;
        public void DebugInitWorld(CallReducerFlags flags) => DebugInitWorldFlags = flags;
    }
}
