// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DebugGiveCrystalHandler(ReducerEventContext ctx, ulong playerId, CrystalType crystalType);
        public event DebugGiveCrystalHandler? OnDebugGiveCrystal;

        public void DebugGiveCrystal(ulong playerId, CrystalType crystalType)
        {
            conn.InternalCallReducer(new Reducer.DebugGiveCrystal(playerId, crystalType), this.SetCallReducerFlags.DebugGiveCrystalFlags);
        }

        public bool InvokeDebugGiveCrystal(ReducerEventContext ctx, Reducer.DebugGiveCrystal args)
        {
            if (OnDebugGiveCrystal == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDebugGiveCrystal(
                ctx,
                args.PlayerId,
                args.CrystalType
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DebugGiveCrystal : Reducer, IReducerArgs
        {
            [DataMember(Name = "player_id")]
            public ulong PlayerId;
            [DataMember(Name = "crystal_type")]
            public CrystalType CrystalType;

            public DebugGiveCrystal(
                ulong PlayerId,
                CrystalType CrystalType
            )
            {
                this.PlayerId = PlayerId;
                this.CrystalType = CrystalType;
            }

            public DebugGiveCrystal()
            {
            }

            string IReducerArgs.ReducerName => "debug_give_crystal";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags DebugGiveCrystalFlags;
        public void DebugGiveCrystal(CallReducerFlags flags) => DebugGiveCrystalFlags = flags;
    }
}
