// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DebugTestSpawnPositionsHandler(ReducerEventContext ctx);
        public event DebugTestSpawnPositionsHandler? OnDebugTestSpawnPositions;

        public void DebugTestSpawnPositions()
        {
            conn.InternalCallReducer(new Reducer.DebugTestSpawnPositions(), this.SetCallReducerFlags.DebugTestSpawnPositionsFlags);
        }

        public bool InvokeDebugTestSpawnPositions(ReducerEventContext ctx, Reducer.DebugTestSpawnPositions args)
        {
            if (OnDebugTestSpawnPositions == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDebugTestSpawnPositions(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DebugTestSpawnPositions : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "debug_test_spawn_positions";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags DebugTestSpawnPositionsFlags;
        public void DebugTestSpawnPositions(CallReducerFlags flags) => DebugTestSpawnPositionsFlags = flags;
    }
}
