// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DebugQuantaStatusHandler(ReducerEventContext ctx);
        public event DebugQuantaStatusHandler? OnDebugQuantaStatus;

        public void DebugQuantaStatus()
        {
            conn.InternalCallReducer(new Reducer.DebugQuantaStatus(), this.SetCallReducerFlags.DebugQuantaStatusFlags);
        }

        public bool InvokeDebugQuantaStatus(ReducerEventContext ctx, Reducer.DebugQuantaStatus args)
        {
            if (OnDebugQuantaStatus == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDebugQuantaStatus(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DebugQuantaStatus : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "debug_quanta_status";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags DebugQuantaStatusFlags;
        public void DebugQuantaStatus(CallReducerFlags flags) => DebugQuantaStatusFlags = flags;
    }
}
