// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DebugCreateStorageDeviceHandler(ReducerEventContext ctx, ulong playerId, float x, float y, float z, string deviceName);
        public event DebugCreateStorageDeviceHandler? OnDebugCreateStorageDevice;

        public void DebugCreateStorageDevice(ulong playerId, float x, float y, float z, string deviceName)
        {
            conn.InternalCallReducer(new Reducer.DebugCreateStorageDevice(playerId, x, y, z, deviceName), this.SetCallReducerFlags.DebugCreateStorageDeviceFlags);
        }

        public bool InvokeDebugCreateStorageDevice(ReducerEventContext ctx, Reducer.DebugCreateStorageDevice args)
        {
            if (OnDebugCreateStorageDevice == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDebugCreateStorageDevice(
                ctx,
                args.PlayerId,
                args.X,
                args.Y,
                args.Z,
                args.DeviceName
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DebugCreateStorageDevice : Reducer, IReducerArgs
        {
            [DataMember(Name = "player_id")]
            public ulong PlayerId;
            [DataMember(Name = "x")]
            public float X;
            [DataMember(Name = "y")]
            public float Y;
            [DataMember(Name = "z")]
            public float Z;
            [DataMember(Name = "device_name")]
            public string DeviceName;

            public DebugCreateStorageDevice(
                ulong PlayerId,
                float X,
                float Y,
                float Z,
                string DeviceName
            )
            {
                this.PlayerId = PlayerId;
                this.X = X;
                this.Y = Y;
                this.Z = Z;
                this.DeviceName = DeviceName;
            }

            public DebugCreateStorageDevice()
            {
                this.DeviceName = "";
            }

            string IReducerArgs.ReducerName => "debug_create_storage_device";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags DebugCreateStorageDeviceFlags;
        public void DebugCreateStorageDevice(CallReducerFlags flags) => DebugCreateStorageDeviceFlags = flags;
    }
}
