// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DebugTestSimpleEnergyEmissionHandler(ReducerEventContext ctx);
        public event DebugTestSimpleEnergyEmissionHandler? OnDebugTestSimpleEnergyEmission;

        public void DebugTestSimpleEnergyEmission()
        {
            conn.InternalCallReducer(new Reducer.DebugTestSimpleEnergyEmission(), this.SetCallReducerFlags.DebugTestSimpleEnergyEmissionFlags);
        }

        public bool InvokeDebugTestSimpleEnergyEmission(ReducerEventContext ctx, Reducer.DebugTestSimpleEnergyEmission args)
        {
            if (OnDebugTestSimpleEnergyEmission == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDebugTestSimpleEnergyEmission(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DebugTestSimpleEnergyEmission : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "debug_test_simple_energy_emission";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags DebugTestSimpleEnergyEmissionFlags;
        public void DebugTestSimpleEnergyEmission(CallReducerFlags flags) => DebugTestSimpleEnergyEmissionFlags = flags;
    }
}
