// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void EmitQuantaOrbHandler(ReducerEventContext ctx, WorldCoords worldCoords, DbVector3 circuitPosition);
        public event EmitQuantaOrbHandler? OnEmitQuantaOrb;

        public void EmitQuantaOrb(WorldCoords worldCoords, DbVector3 circuitPosition)
        {
            conn.InternalCallReducer(new Reducer.EmitQuantaOrb(worldCoords, circuitPosition), this.SetCallReducerFlags.EmitQuantaOrbFlags);
        }

        public bool InvokeEmitQuantaOrb(ReducerEventContext ctx, Reducer.EmitQuantaOrb args)
        {
            if (OnEmitQuantaOrb == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnEmitQuantaOrb(
                ctx,
                args.WorldCoords,
                args.CircuitPosition
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class EmitQuantaOrb : Reducer, IReducerArgs
        {
            [DataMember(Name = "world_coords")]
            public WorldCoords WorldCoords;
            [DataMember(Name = "circuit_position")]
            public DbVector3 CircuitPosition;

            public EmitQuantaOrb(
                WorldCoords WorldCoords,
                DbVector3 CircuitPosition
            )
            {
                this.WorldCoords = WorldCoords;
                this.CircuitPosition = CircuitPosition;
            }

            public EmitQuantaOrb()
            {
                this.WorldCoords = new();
                this.CircuitPosition = new();
            }

            string IReducerArgs.ReducerName => "emit_quanta_orb";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags EmitQuantaOrbFlags;
        public void EmitQuantaOrb(CallReducerFlags flags) => EmitQuantaOrbFlags = flags;
    }
}
