// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void EmitWavePacketOrbHandler(ReducerEventContext ctx, WorldCoords worldCoords, DbVector3 circuitPosition);
        public event EmitWavePacketOrbHandler? OnEmitWavePacketOrb;

        public void EmitWavePacketOrb(WorldCoords worldCoords, DbVector3 circuitPosition)
        {
            conn.InternalCallReducer(new Reducer.EmitWavePacketOrb(worldCoords, circuitPosition), this.SetCallReducerFlags.EmitWavePacketOrbFlags);
        }

        public bool InvokeEmitWavePacketOrb(ReducerEventContext ctx, Reducer.EmitWavePacketOrb args)
        {
            if (OnEmitWavePacketOrb == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnEmitWavePacketOrb(
                ctx,
                args.WorldCoords,
                args.CircuitPosition
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class EmitWavePacketOrb : Reducer, IReducerArgs
        {
            [DataMember(Name = "world_coords")]
            public WorldCoords WorldCoords;
            [DataMember(Name = "circuit_position")]
            public DbVector3 CircuitPosition;

            public EmitWavePacketOrb(
                WorldCoords WorldCoords,
                DbVector3 CircuitPosition
            )
            {
                this.WorldCoords = WorldCoords;
                this.CircuitPosition = CircuitPosition;
            }

            public EmitWavePacketOrb()
            {
                this.WorldCoords = new();
                this.CircuitPosition = new();
            }

            string IReducerArgs.ReducerName => "emit_wave_packet_orb";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags EmitWavePacketOrbFlags;
        public void EmitWavePacketOrb(CallReducerFlags flags) => EmitWavePacketOrbFlags = flags;
    }
}
