// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void EmitWavePacketSourceHandler(ReducerEventContext ctx, WorldCoords worldCoords, DbVector3 sourcePosition);
        public event EmitWavePacketSourceHandler? OnEmitWavePacketSource;

        public void EmitWavePacketSource(WorldCoords worldCoords, DbVector3 sourcePosition)
        {
            conn.InternalCallReducer(new Reducer.EmitWavePacketSource(worldCoords, sourcePosition), this.SetCallReducerFlags.EmitWavePacketSourceFlags);
        }

        public bool InvokeEmitWavePacketSource(ReducerEventContext ctx, Reducer.EmitWavePacketSource args)
        {
            if (OnEmitWavePacketSource == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnEmitWavePacketSource(
                ctx,
                args.WorldCoords,
                args.SourcePosition
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class EmitWavePacketSource : Reducer, IReducerArgs
        {
            [DataMember(Name = "world_coords")]
            public WorldCoords WorldCoords;
            [DataMember(Name = "source_position")]
            public DbVector3 SourcePosition;

            public EmitWavePacketSource(
                WorldCoords WorldCoords,
                DbVector3 SourcePosition
            )
            {
                this.WorldCoords = WorldCoords;
                this.SourcePosition = SourcePosition;
            }

            public EmitWavePacketSource()
            {
                this.WorldCoords = new();
                this.SourcePosition = new();
            }

            string IReducerArgs.ReducerName => "emit_wave_packet_source";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags EmitWavePacketSourceFlags;
        public void EmitWavePacketSource(CallReducerFlags flags) => EmitWavePacketSourceFlags = flags;
    }
}
