// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void EnterGameHandler(ReducerEventContext ctx, string playerName);
        public event EnterGameHandler? OnEnterGame;

        public void EnterGame(string playerName)
        {
            conn.InternalCallReducer(new Reducer.EnterGame(playerName), this.SetCallReducerFlags.EnterGameFlags);
        }

        public bool InvokeEnterGame(ReducerEventContext ctx, Reducer.EnterGame args)
        {
            if (OnEnterGame == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnEnterGame(
                ctx,
                args.PlayerName
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class EnterGame : Reducer, IReducerArgs
        {
            [DataMember(Name = "player_name")]
            public string PlayerName;

            public EnterGame(string PlayerName)
            {
                this.PlayerName = PlayerName;
            }

            public EnterGame()
            {
                this.PlayerName = "";
            }

            string IReducerArgs.ReducerName => "enter_game";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags EnterGameFlags;
        public void EnterGame(CallReducerFlags flags) => EnterGameFlags = flags;
    }
}
