// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ExtractWavePacketHandler(ReducerEventContext ctx);
        public event ExtractWavePacketHandler? OnExtractWavePacket;

        public void ExtractWavePacket()
        {
            conn.InternalCallReducer(new Reducer.ExtractWavePacket(), this.SetCallReducerFlags.ExtractWavePacketFlags);
        }

        public bool InvokeExtractWavePacket(ReducerEventContext ctx, Reducer.ExtractWavePacket args)
        {
            if (OnExtractWavePacket == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnExtractWavePacket(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ExtractWavePacket : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "extract_wave_packet";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ExtractWavePacketFlags;
        public void ExtractWavePacket(CallReducerFlags flags) => ExtractWavePacketFlags = flags;
    }
}
