// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ExtractPacketsV2Handler(ReducerEventContext ctx, ulong sessionId);
        public event ExtractPacketsV2Handler? OnExtractPacketsV2;

        public void ExtractPacketsV2(ulong sessionId)
        {
            conn.InternalCallReducer(new Reducer.ExtractPacketsV2(sessionId), this.SetCallReducerFlags.ExtractPacketsV2Flags);
        }

        public bool InvokeExtractPacketsV2(ReducerEventContext ctx, Reducer.ExtractPacketsV2 args)
        {
            if (OnExtractPacketsV2 == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnExtractPacketsV2(
                ctx,
                args.SessionId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ExtractPacketsV2 : Reducer, IReducerArgs
        {
            [DataMember(Name = "session_id")]
            public ulong SessionId;

            public ExtractPacketsV2(ulong SessionId)
            {
                this.SessionId = SessionId;
            }

            public ExtractPacketsV2()
            {
            }

            string IReducerArgs.ReducerName => "extract_packets_v2";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ExtractPacketsV2Flags;
        public void ExtractPacketsV2(CallReducerFlags flags) => ExtractPacketsV2Flags = flags;
    }
}
