// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void GameLoopHandler(ReducerEventContext ctx, GameLoopSchedule arg);
        public event GameLoopHandler? OnGameLoop;

        public void GameLoop(GameLoopSchedule arg)
        {
            conn.InternalCallReducer(new Reducer.GameLoop(arg), this.SetCallReducerFlags.GameLoopFlags);
        }

        public bool InvokeGameLoop(ReducerEventContext ctx, Reducer.GameLoop args)
        {
            if (OnGameLoop == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnGameLoop(
                ctx,
                args.Arg
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class GameLoop : Reducer, IReducerArgs
        {
            [DataMember(Name = "_arg")]
            public GameLoopSchedule Arg;

            public GameLoop(GameLoopSchedule Arg)
            {
                this.Arg = Arg;
            }

            public GameLoop()
            {
                this.Arg = new();
            }

            string IReducerArgs.ReducerName => "game_loop";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags GameLoopFlags;
        public void GameLoop(CallReducerFlags flags) => GameLoopFlags = flags;
    }
}
