// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void GetPlayerEnergyInventoryHandler(ReducerEventContext ctx, uint playerId);
        public event GetPlayerEnergyInventoryHandler? OnGetPlayerEnergyInventory;

        public void GetPlayerEnergyInventory(uint playerId)
        {
            conn.InternalCallReducer(new Reducer.GetPlayerEnergyInventory(playerId), this.SetCallReducerFlags.GetPlayerEnergyInventoryFlags);
        }

        public bool InvokeGetPlayerEnergyInventory(ReducerEventContext ctx, Reducer.GetPlayerEnergyInventory args)
        {
            if (OnGetPlayerEnergyInventory == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnGetPlayerEnergyInventory(
                ctx,
                args.PlayerId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class GetPlayerEnergyInventory : Reducer, IReducerArgs
        {
            [DataMember(Name = "player_id")]
            public uint PlayerId;

            public GetPlayerEnergyInventory(uint PlayerId)
            {
                this.PlayerId = PlayerId;
            }

            public GetPlayerEnergyInventory()
            {
            }

            string IReducerArgs.ReducerName => "get_player_energy_inventory";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags GetPlayerEnergyInventoryFlags;
        public void GetPlayerEnergyInventory(CallReducerFlags flags) => GetPlayerEnergyInventoryFlags = flags;
    }
}
