// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void InitHandler(ReducerEventContext ctx);
        public event InitHandler? OnInit;

        public void Init()
        {
            conn.InternalCallReducer(new Reducer.Init(), this.SetCallReducerFlags.InitFlags);
        }

        public bool InvokeInit(ReducerEventContext ctx, Reducer.Init args)
        {
            if (OnInit == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnInit(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class Init : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "init";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags InitFlags;
        public void Init(CallReducerFlags flags) => InitFlags = flags;
    }
}
