// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void InitializePlayerInventoryHandler(ReducerEventContext ctx);
        public event InitializePlayerInventoryHandler? OnInitializePlayerInventory;

        public void InitializePlayerInventory()
        {
            conn.InternalCallReducer(new Reducer.InitializePlayerInventory(), this.SetCallReducerFlags.InitializePlayerInventoryFlags);
        }

        public bool InvokeInitializePlayerInventory(ReducerEventContext ctx, Reducer.InitializePlayerInventory args)
        {
            if (OnInitializePlayerInventory == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnInitializePlayerInventory(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class InitializePlayerInventory : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "initialize_player_inventory";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags InitializePlayerInventoryFlags;
        public void InitializePlayerInventory(CallReducerFlags flags) => InitializePlayerInventoryFlags = flags;
    }
}
