// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void InitiateTransferHandler(ReducerEventContext ctx, System.Collections.Generic.List<WavePacketSample> composition, ulong destinationDeviceId);
        public event InitiateTransferHandler? OnInitiateTransfer;

        public void InitiateTransfer(System.Collections.Generic.List<WavePacketSample> composition, ulong destinationDeviceId)
        {
            conn.InternalCallReducer(new Reducer.InitiateTransfer(composition, destinationDeviceId), this.SetCallReducerFlags.InitiateTransferFlags);
        }

        public bool InvokeInitiateTransfer(ReducerEventContext ctx, Reducer.InitiateTransfer args)
        {
            if (OnInitiateTransfer == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnInitiateTransfer(
                ctx,
                args.Composition,
                args.DestinationDeviceId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class InitiateTransfer : Reducer, IReducerArgs
        {
            [DataMember(Name = "composition")]
            public System.Collections.Generic.List<WavePacketSample> Composition;
            [DataMember(Name = "destination_device_id")]
            public ulong DestinationDeviceId;

            public InitiateTransfer(
                System.Collections.Generic.List<WavePacketSample> Composition,
                ulong DestinationDeviceId
            )
            {
                this.Composition = Composition;
                this.DestinationDeviceId = DestinationDeviceId;
            }

            public InitiateTransfer()
            {
                this.Composition = new();
            }

            string IReducerArgs.ReducerName => "initiate_transfer";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags InitiateTransferFlags;
        public void InitiateTransfer(CallReducerFlags flags) => InitiateTransferFlags = flags;
    }
}
