// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void LoginAccountHandler(ReducerEventContext ctx, string username, string password);
        public event LoginAccountHandler? OnLoginAccount;

        public void LoginAccount(string username, string password)
        {
            conn.InternalCallReducer(new Reducer.LoginAccount(username, password), this.SetCallReducerFlags.LoginAccountFlags);
        }

        public bool InvokeLoginAccount(ReducerEventContext ctx, Reducer.LoginAccount args)
        {
            if (OnLoginAccount == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnLoginAccount(
                ctx,
                args.Username,
                args.Password
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class LoginAccount : Reducer, IReducerArgs
        {
            [DataMember(Name = "username")]
            public string Username;
            [DataMember(Name = "password")]
            public string Password;

            public LoginAccount(
                string Username,
                string Password
            )
            {
                this.Username = Username;
                this.Password = Password;
            }

            public LoginAccount()
            {
                this.Username = "";
                this.Password = "";
            }

            string IReducerArgs.ReducerName => "login_account";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags LoginAccountFlags;
        public void LoginAccount(CallReducerFlags flags) => LoginAccountFlags = flags;
    }
}
