// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RegisterAccountHandler(ReducerEventContext ctx, string username, string password);
        public event RegisterAccountHandler? OnRegisterAccount;

        public void RegisterAccount(string username, string password)
        {
            conn.InternalCallReducer(new Reducer.RegisterAccount(username, password), this.SetCallReducerFlags.RegisterAccountFlags);
        }

        public bool InvokeRegisterAccount(ReducerEventContext ctx, Reducer.RegisterAccount args)
        {
            if (OnRegisterAccount == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnRegisterAccount(
                ctx,
                args.Username,
                args.Password
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RegisterAccount : Reducer, IReducerArgs
        {
            [DataMember(Name = "username")]
            public string Username;
            [DataMember(Name = "password")]
            public string Password;

            public RegisterAccount(
                string Username,
                string Password
            )
            {
                this.Username = Username;
                this.Password = Password;
            }

            public RegisterAccount()
            {
                this.Username = "";
                this.Password = "";
            }

            string IReducerArgs.ReducerName => "register_account";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags RegisterAccountFlags;
        public void RegisterAccount(CallReducerFlags flags) => RegisterAccountFlags = flags;
    }
}
