// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RegisterHandler(ReducerEventContext ctx, string username, string password);
        public event RegisterHandler? OnRegister;

        public void Register(string username, string password)
        {
            conn.InternalCallReducer(new Reducer.Register(username, password), this.SetCallReducerFlags.RegisterFlags);
        }

        public bool InvokeRegister(ReducerEventContext ctx, Reducer.Register args)
        {
            if (OnRegister == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnRegister(
                ctx,
                args.Username,
                args.Password
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class Register : Reducer, IReducerArgs
        {
            [DataMember(Name = "username")]
            public string Username;
            [DataMember(Name = "password")]
            public string Password;

            public Register(
                string Username,
                string Password
            )
            {
                this.Username = Username;
                this.Password = Password;
            }

            public Register()
            {
                this.Username = "";
                this.Password = "";
            }

            string IReducerArgs.ReducerName => "register";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags RegisterFlags;
        public void Register(CallReducerFlags flags) => RegisterFlags = flags;
    }
}
