// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ReportOrbLandingHandler(ReducerEventContext ctx, ulong orbId, DbVector3 landingPosition);
        public event ReportOrbLandingHandler? OnReportOrbLanding;

        public void ReportOrbLanding(ulong orbId, DbVector3 landingPosition)
        {
            conn.InternalCallReducer(new Reducer.ReportOrbLanding(orbId, landingPosition), this.SetCallReducerFlags.ReportOrbLandingFlags);
        }

        public bool InvokeReportOrbLanding(ReducerEventContext ctx, Reducer.ReportOrbLanding args)
        {
            if (OnReportOrbLanding == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnReportOrbLanding(
                ctx,
                args.OrbId,
                args.LandingPosition
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ReportOrbLanding : Reducer, IReducerArgs
        {
            [DataMember(Name = "orb_id")]
            public ulong OrbId;
            [DataMember(Name = "landing_position")]
            public DbVector3 LandingPosition;

            public ReportOrbLanding(
                ulong OrbId,
                DbVector3 LandingPosition
            )
            {
                this.OrbId = OrbId;
                this.LandingPosition = LandingPosition;
            }

            public ReportOrbLanding()
            {
                this.LandingPosition = new();
            }

            string IReducerArgs.ReducerName => "report_orb_landing";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ReportOrbLandingFlags;
        public void ReportOrbLanding(CallReducerFlags flags) => ReportOrbLandingFlags = flags;
    }
}
