// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RestoreSessionHandler(ReducerEventContext ctx, string sessionToken);
        public event RestoreSessionHandler? OnRestoreSession;

        public void RestoreSession(string sessionToken)
        {
            conn.InternalCallReducer(new Reducer.RestoreSession(sessionToken), this.SetCallReducerFlags.RestoreSessionFlags);
        }

        public bool InvokeRestoreSession(ReducerEventContext ctx, Reducer.RestoreSession args)
        {
            if (OnRestoreSession == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnRestoreSession(
                ctx,
                args.SessionToken
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RestoreSession : Reducer, IReducerArgs
        {
            [DataMember(Name = "session_token")]
            public string SessionToken;

            public RestoreSession(string SessionToken)
            {
                this.SessionToken = SessionToken;
            }

            public RestoreSession()
            {
                this.SessionToken = "";
            }

            string IReducerArgs.ReducerName => "restore_session";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags RestoreSessionFlags;
        public void RestoreSession(CallReducerFlags flags) => RestoreSessionFlags = flags;
    }
}
