// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SendPlayerChatHandler(ReducerEventContext ctx, string content);
        public event SendPlayerChatHandler? OnSendPlayerChat;

        public void SendPlayerChat(string content)
        {
            conn.InternalCallReducer(new Reducer.SendPlayerChat(content), this.SetCallReducerFlags.SendPlayerChatFlags);
        }

        public bool InvokeSendPlayerChat(ReducerEventContext ctx, Reducer.SendPlayerChat args)
        {
            if (OnSendPlayerChat == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSendPlayerChat(
                ctx,
                args.Content
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SendPlayerChat : Reducer, IReducerArgs
        {
            [DataMember(Name = "content")]
            public string Content;

            public SendPlayerChat(string Content)
            {
                this.Content = Content;
            }

            public SendPlayerChat()
            {
                this.Content = "";
            }

            string IReducerArgs.ReducerName => "send_player_chat";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags SendPlayerChatFlags;
        public void SendPlayerChat(CallReducerFlags flags) => SendPlayerChatFlags = flags;
    }
}
