// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SpawnMainSpiresHandler(ReducerEventContext ctx, int worldX, int worldY, int worldZ);
        public event SpawnMainSpiresHandler? OnSpawnMainSpires;

        public void SpawnMainSpires(int worldX, int worldY, int worldZ)
        {
            conn.InternalCallReducer(new Reducer.SpawnMainSpires(worldX, worldY, worldZ), this.SetCallReducerFlags.SpawnMainSpiresFlags);
        }

        public bool InvokeSpawnMainSpires(ReducerEventContext ctx, Reducer.SpawnMainSpires args)
        {
            if (OnSpawnMainSpires == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSpawnMainSpires(
                ctx,
                args.WorldX,
                args.WorldY,
                args.WorldZ
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SpawnMainSpires : Reducer, IReducerArgs
        {
            [DataMember(Name = "world_x")]
            public int WorldX;
            [DataMember(Name = "world_y")]
            public int WorldY;
            [DataMember(Name = "world_z")]
            public int WorldZ;

            public SpawnMainSpires(
                int WorldX,
                int WorldY,
                int WorldZ
            )
            {
                this.WorldX = WorldX;
                this.WorldY = WorldY;
                this.WorldZ = WorldZ;
            }

            public SpawnMainSpires()
            {
            }

            string IReducerArgs.ReducerName => "spawn_main_spires";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags SpawnMainSpiresFlags;
        public void SpawnMainSpires(CallReducerFlags flags) => SpawnMainSpiresFlags = flags;
    }
}
