// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void Spawn6CardinalCircuitsHandler(ReducerEventContext ctx, int worldX, int worldY, int worldZ);
        public event Spawn6CardinalCircuitsHandler? OnSpawn6CardinalCircuits;

        public void Spawn6CardinalCircuits(int worldX, int worldY, int worldZ)
        {
            conn.InternalCallReducer(new Reducer.Spawn6CardinalCircuits(worldX, worldY, worldZ), this.SetCallReducerFlags.Spawn6CardinalCircuitsFlags);
        }

        public bool InvokeSpawn6CardinalCircuits(ReducerEventContext ctx, Reducer.Spawn6CardinalCircuits args)
        {
            if (OnSpawn6CardinalCircuits == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSpawn6CardinalCircuits(
                ctx,
                args.WorldX,
                args.WorldY,
                args.WorldZ
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class Spawn6CardinalCircuits : Reducer, IReducerArgs
        {
            [DataMember(Name = "world_x")]
            public int WorldX;
            [DataMember(Name = "world_y")]
            public int WorldY;
            [DataMember(Name = "world_z")]
            public int WorldZ;

            public Spawn6CardinalCircuits(
                int WorldX,
                int WorldY,
                int WorldZ
            )
            {
                this.WorldX = WorldX;
                this.WorldY = WorldY;
                this.WorldZ = WorldZ;
            }

            public Spawn6CardinalCircuits()
            {
            }

            string IReducerArgs.ReducerName => "spawn_6_cardinal_circuits";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags Spawn6CardinalCircuitsFlags;
        public void Spawn6CardinalCircuits(CallReducerFlags flags) => Spawn6CardinalCircuitsFlags = flags;
    }
}
