// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SpawnTestOrbHandler(ReducerEventContext ctx, float x, float y, float z, byte frequency, uint packetCount);
        public event SpawnTestOrbHandler? OnSpawnTestOrb;

        public void SpawnTestOrb(float x, float y, float z, byte frequency, uint packetCount)
        {
            conn.InternalCallReducer(new Reducer.SpawnTestOrb(x, y, z, frequency, packetCount), this.SetCallReducerFlags.SpawnTestOrbFlags);
        }

        public bool InvokeSpawnTestOrb(ReducerEventContext ctx, Reducer.SpawnTestOrb args)
        {
            if (OnSpawnTestOrb == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSpawnTestOrb(
                ctx,
                args.X,
                args.Y,
                args.Z,
                args.Frequency,
                args.PacketCount
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SpawnTestOrb : Reducer, IReducerArgs
        {
            [DataMember(Name = "x")]
            public float X;
            [DataMember(Name = "y")]
            public float Y;
            [DataMember(Name = "z")]
            public float Z;
            [DataMember(Name = "frequency")]
            public byte Frequency;
            [DataMember(Name = "packet_count")]
            public uint PacketCount;

            public SpawnTestOrb(
                float X,
                float Y,
                float Z,
                byte Frequency,
                uint PacketCount
            )
            {
                this.X = X;
                this.Y = Y;
                this.Z = Z;
                this.Frequency = Frequency;
                this.PacketCount = PacketCount;
            }

            public SpawnTestOrb()
            {
            }

            string IReducerArgs.ReducerName => "spawn_test_orb";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags SpawnTestOrbFlags;
        public void SpawnTestOrb(CallReducerFlags flags) => SpawnTestOrbFlags = flags;
    }
}
