// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void StartGameLoopHandler(ReducerEventContext ctx);
        public event StartGameLoopHandler? OnStartGameLoop;

        public void StartGameLoop()
        {
            conn.InternalCallReducer(new Reducer.StartGameLoop(), this.SetCallReducerFlags.StartGameLoopFlags);
        }

        public bool InvokeStartGameLoop(ReducerEventContext ctx, Reducer.StartGameLoop args)
        {
            if (OnStartGameLoop == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnStartGameLoop(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class StartGameLoop : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "start_game_loop";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags StartGameLoopFlags;
        public void StartGameLoop(CallReducerFlags flags) => StartGameLoopFlags = flags;
    }
}
