// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void StartMiningV2Handler(ReducerEventContext ctx, ulong sourceId, System.Collections.Generic.List<WavePacketSample> crystalComposition);
        public event StartMiningV2Handler? OnStartMiningV2;

        public void StartMiningV2(ulong sourceId, System.Collections.Generic.List<WavePacketSample> crystalComposition)
        {
            conn.InternalCallReducer(new Reducer.StartMiningV2(sourceId, crystalComposition), this.SetCallReducerFlags.StartMiningV2Flags);
        }

        public bool InvokeStartMiningV2(ReducerEventContext ctx, Reducer.StartMiningV2 args)
        {
            if (OnStartMiningV2 == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnStartMiningV2(
                ctx,
                args.SourceId,
                args.CrystalComposition
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class StartMiningV2 : Reducer, IReducerArgs
        {
            [DataMember(Name = "source_id")]
            public ulong SourceId;
            [DataMember(Name = "crystal_composition")]
            public System.Collections.Generic.List<WavePacketSample> CrystalComposition;

            public StartMiningV2(
                ulong SourceId,
                System.Collections.Generic.List<WavePacketSample> CrystalComposition
            )
            {
                this.SourceId = SourceId;
                this.CrystalComposition = CrystalComposition;
            }

            public StartMiningV2()
            {
                this.CrystalComposition = new();
            }

            string IReducerArgs.ReducerName => "start_mining_v2";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags StartMiningV2Flags;
        public void StartMiningV2(CallReducerFlags flags) => StartMiningV2Flags = flags;
    }
}
