// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void StartMiningHandler(ReducerEventContext ctx, ulong orbId);
        public event StartMiningHandler? OnStartMining;

        public void StartMining(ulong orbId)
        {
            conn.InternalCallReducer(new Reducer.StartMining(orbId), this.SetCallReducerFlags.StartMiningFlags);
        }

        public bool InvokeStartMining(ReducerEventContext ctx, Reducer.StartMining args)
        {
            if (OnStartMining == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnStartMining(
                ctx,
                args.OrbId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class StartMining : Reducer, IReducerArgs
        {
            [DataMember(Name = "orb_id")]
            public ulong OrbId;

            public StartMining(ulong OrbId)
            {
                this.OrbId = OrbId;
            }

            public StartMining()
            {
            }

            string IReducerArgs.ReducerName => "start_mining";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags StartMiningFlags;
        public void StartMining(CallReducerFlags flags) => StartMiningFlags = flags;
    }
}
