// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void StopGameLoopHandler(ReducerEventContext ctx);
        public event StopGameLoopHandler? OnStopGameLoop;

        public void StopGameLoop()
        {
            conn.InternalCallReducer(new Reducer.StopGameLoop(), this.SetCallReducerFlags.StopGameLoopFlags);
        }

        public bool InvokeStopGameLoop(ReducerEventContext ctx, Reducer.StopGameLoop args)
        {
            if (OnStopGameLoop == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnStopGameLoop(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class StopGameLoop : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "stop_game_loop";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags StopGameLoopFlags;
        public void StopGameLoop(CallReducerFlags flags) => StopGameLoopFlags = flags;
    }
}
