// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void StopMiningHandler(ReducerEventContext ctx);
        public event StopMiningHandler? OnStopMining;

        public void StopMining()
        {
            conn.InternalCallReducer(new Reducer.StopMining(), this.SetCallReducerFlags.StopMiningFlags);
        }

        public bool InvokeStopMining(ReducerEventContext ctx, Reducer.StopMining args)
        {
            if (OnStopMining == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnStopMining(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class StopMining : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "stop_mining";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags StopMiningFlags;
        public void StopMining(CallReducerFlags flags) => StopMiningFlags = flags;
    }
}
