// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void WorldSpherePulseHandler(ReducerEventContext ctx, int worldX, int worldY, int worldZ);
        public event WorldSpherePulseHandler? OnWorldSpherePulse;

        public void WorldSpherePulse(int worldX, int worldY, int worldZ)
        {
            conn.InternalCallReducer(new Reducer.WorldSpherePulse(worldX, worldY, worldZ), this.SetCallReducerFlags.WorldSpherePulseFlags);
        }

        public bool InvokeWorldSpherePulse(ReducerEventContext ctx, Reducer.WorldSpherePulse args)
        {
            if (OnWorldSpherePulse == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnWorldSpherePulse(
                ctx,
                args.WorldX,
                args.WorldY,
                args.WorldZ
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class WorldSpherePulse : Reducer, IReducerArgs
        {
            [DataMember(Name = "world_x")]
            public int WorldX;
            [DataMember(Name = "world_y")]
            public int WorldY;
            [DataMember(Name = "world_z")]
            public int WorldZ;

            public WorldSpherePulse(
                int WorldX,
                int WorldY,
                int WorldZ
            )
            {
                this.WorldX = WorldX;
                this.WorldY = WorldY;
                this.WorldZ = WorldZ;
            }

            public WorldSpherePulse()
            {
            }

            string IReducerArgs.ReducerName => "world_sphere_pulse";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags WorldSpherePulseFlags;
        public void WorldSpherePulse(CallReducerFlags flags) => WorldSpherePulseFlags = flags;
    }
}
