// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class DistributionSphereHandle : RemoteTableHandle<EventContext, DistributionSphere>
        {
            protected override string RemoteTableName => "distribution_sphere";

            public sealed class SphereIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(DistributionSphere row) => row.SphereId;

                public SphereIdUniqueIndex(DistributionSphereHandle table) : base(table) { }
            }

            public readonly SphereIdUniqueIndex SphereId;

            internal DistributionSphereHandle(DbConnection conn) : base(conn)
            {
                SphereId = new(this);
            }

            protected override object GetPrimaryKey(DistributionSphere row) => row.SphereId;
        }

        public readonly DistributionSphereHandle DistributionSphere;
    }
}
