// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class GameLoopScheduleHandle : RemoteTableHandle<EventContext, GameLoopSchedule>
        {
            protected override string RemoteTableName => "game_loop_schedule";

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(GameLoopSchedule row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(GameLoopScheduleHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal GameLoopScheduleHandle(DbConnection conn) : base(conn)
            {
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(GameLoopSchedule row) => row.ScheduledId;
        }

        public readonly GameLoopScheduleHandle GameLoopSchedule;
    }
}
