// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class GameTickCounterHandle : RemoteTableHandle<EventContext, GameTickCounter>
        {
            protected override string RemoteTableName => "game_tick_counter";

            public sealed class IdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(GameTickCounter row) => row.Id;

                public IdUniqueIndex(GameTickCounterHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal GameTickCounterHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(GameTickCounter row) => row.Id;
        }

        public readonly GameTickCounterHandle GameTickCounter;
    }
}
