// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PacketTransferHandle : RemoteTableHandle<EventContext, PacketTransfer>
        {
            protected override string RemoteTableName => "packet_transfer";

            public sealed class TransferIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PacketTransfer row) => row.TransferId;

                public TransferIdUniqueIndex(PacketTransferHandle table) : base(table) { }
            }

            public readonly TransferIdUniqueIndex TransferId;

            internal PacketTransferHandle(DbConnection conn) : base(conn)
            {
                TransferId = new(this);
            }

            protected override object GetPrimaryKey(PacketTransfer row) => row.TransferId;
        }

        public readonly PacketTransferHandle PacketTransfer;
    }
}
