// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerInventoryHandle : RemoteTableHandle<EventContext, PlayerInventory>
        {
            protected override string RemoteTableName => "player_inventory";

            public sealed class PlayerIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PlayerInventory row) => row.PlayerId;

                public PlayerIdUniqueIndex(PlayerInventoryHandle table) : base(table) { }
            }

            public readonly PlayerIdUniqueIndex PlayerId;

            internal PlayerInventoryHandle(DbConnection conn) : base(conn)
            {
                PlayerId = new(this);
            }

            protected override object GetPrimaryKey(PlayerInventory row) => row.PlayerId;
        }

        public readonly PlayerInventoryHandle PlayerInventory;
    }
}
