// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class WavePacketSourceHandle : RemoteTableHandle<EventContext, WavePacketSource>
        {
            protected override string RemoteTableName => "wave_packet_source";

            public sealed class SourceIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(WavePacketSource row) => row.SourceId;

                public SourceIdUniqueIndex(WavePacketSourceHandle table) : base(table) { }
            }

            public readonly SourceIdUniqueIndex SourceId;

            internal WavePacketSourceHandle(DbConnection conn) : base(conn)
            {
                SourceId = new(this);
            }

            protected override object GetPrimaryKey(WavePacketSource row) => row.SourceId;
        }

        public readonly WavePacketSourceHandle WavePacketSource;
    }
}
