// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class WorldHandle : RemoteTableHandle<EventContext, World>
        {
            protected override string RemoteTableName => "world";

            public sealed class WorldIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(World row) => row.WorldId;

                public WorldIdUniqueIndex(WorldHandle table) : base(table) { }
            }

            public readonly WorldIdUniqueIndex WorldId;

            internal WorldHandle(DbConnection conn) : base(conn)
            {
                WorldId = new(this);
            }

            protected override object GetPrimaryKey(World row) => row.WorldId;
        }

        public readonly WorldHandle World;
    }
}
